package com.Atom2Universe.app.games.cosmorun

/**
 * Le catalogue des motifs de piste. Un motif est une petite grille ASCII : 5 colonnes = 5 voies,
 * une ligne = une **rangée**, et une rangée dure [ROW_TIME] secondes de course quelle que soit la
 * vitesse. La première ligne est la plus proche du joueur.
 *
 * ```
 * .  vide                    a  atome au sol            A  atome en altitude (il faut sauter)
 * h  barrière basse (saut)   l  portique (glissade)     d  drone (glissade)
 * *  météore annoncé (saut ou contournement), monde de cristal et nébuleuse
 * s m b  bouclier, aimant, surrégime
 * #  conteneur : dessus praticable ; @ avec un atome dessus ; ^ avec une barrière ; = avec un portique
 * /  rampe montante (à placer juste avant un conteneur, dans la même voie)
 * ```
 * Les `#`, `@`, `^`, `=` empilés verticalement dans une voie forment UN conteneur ; les `/` aussi une rampe.
 */
object CosmoRunPatterns {
    const val ROW_TIME = .16f

    /** Un monde par bit (voir [CosmoRunGame.sectorTheme]). */
    const val ALL = 7
    const val DOCKS = 1
    const val CRYSTAL = 2
    const val NEBULA = 4

    /** [roofed] : posé sur le dessus d'un conteneur plutôt que sur le sol. */
    class Cell(val lane: Int, val row: Int, val length: Int, val type: CosmoRunGame.EntityType, val roofed: Boolean = false)

    /**
     * [entry] / [exit] : voies libres de tout obstacle au sol dans les deux premières / dernières rangées.
     * [exitRoof] : voies où l'on peut finir sur un toit. [usesRoof] : le motif demande une rampe.
     */
    class Pattern(val name: String, val tier: Int, val themes: Int, val weight: Int, val rows: Int,
                  val cells: List<Cell>, val entry: Int, val exit: Int, val exitRoof: Int, val breather: Boolean) {
        val hazardCount get() = cells.count { it.type.hazard }
        val usesRoof get() = cells.any { it.type == CosmoRunGame.EntityType.RAMP }
    }

    private class Def(val name: String, val tier: Int, val themes: Int, val weight: Int, val breather: Boolean,
                      val grid: List<String>)

    private val defs = ArrayList<Def>()

    private fun pattern(name: String, tier: Int, themes: Int = ALL, weight: Int = 3, breather: Boolean = false,
                        grid: String) {
        defs.add(Def(name, tier, themes, weight, breather, grid.trimIndent().lines().filter { it.isNotBlank() }.map { it.trim() }))
    }

    /** Lit une grille en cellules ; fusionne les conteneurs et les rampes empilés. */
    fun parse(name: String, tier: Int, themes: Int, weight: Int, breather: Boolean, grid: List<String>): Pattern {
        require(grid.all { it.length == CosmoRunGame.NUM_LANES }) { "$name : chaque ligne doit avoir 5 colonnes" }
        val cells = ArrayList<Cell>()
        val rows = grid.size
        for (lane in 0 until CosmoRunGame.NUM_LANES) {
            var row = 0
            while (row < rows) {
                val ch = grid[row][lane]
                when (ch) {
                    '.' -> row++
                    '#', '@', '^', '=', '/' -> {
                        val ramp = ch == '/'
                        var end = row
                        while (end < rows && grid[end][lane] in "#@^=/" && (grid[end][lane] == '/') == ramp) end++
                        cells.add(Cell(lane, row, end - row,
                            if (ramp) CosmoRunGame.EntityType.RAMP else CosmoRunGame.EntityType.CONTAINER))
                        if (!ramp) for (r in row until end) when (grid[r][lane]) {
                            '@' -> cells.add(Cell(lane, r, 1, CosmoRunGame.EntityType.ATOM, roofed = true))
                            '^' -> cells.add(Cell(lane, r, 1, CosmoRunGame.EntityType.HURDLE, roofed = true))
                            '=' -> cells.add(Cell(lane, r, 1, CosmoRunGame.EntityType.LASER, roofed = true))
                        }
                        row = end
                    }
                    else -> {
                        val type = when (ch) {
                            'a' -> CosmoRunGame.EntityType.ATOM
                            'A' -> CosmoRunGame.EntityType.ATOM_HIGH
                            'h' -> CosmoRunGame.EntityType.HURDLE
                            'l' -> CosmoRunGame.EntityType.LASER
                            'd' -> CosmoRunGame.EntityType.DRONE
                            '*' -> CosmoRunGame.EntityType.METEOR
                            's' -> CosmoRunGame.EntityType.SHIELD
                            'm' -> CosmoRunGame.EntityType.MAGNET
                            'b' -> CosmoRunGame.EntityType.BOOST
                            else -> error("$name : caractère « $ch » inconnu")
                        }
                        cells.add(Cell(lane, row, 1, type)); row++
                    }
                }
            }
        }
        var exitRoof = 0
        for (c in cells) if (c.type == CosmoRunGame.EntityType.CONTAINER && c.row + c.length >= rows - 1) exitRoof = exitRoof or (1 shl c.lane)
        return Pattern(name, tier, themes, weight, rows, cells, openLanes(cells, 0, minOf(2, rows)),
            openLanes(cells, maxOf(rows - 2, 0), rows), exitRoof, breather)
    }

    /**
     * Voies sans conteneur ni rampe dans les rangées [from] à [to] exclu : l'entrée ou la sortie du motif.
     * Une barrière ou un portique ne ferme pas une voie : on l'a lu de loin et on saute ou on glisse.
     */
    private fun openLanes(cells: List<Cell>, from: Int, to: Int): Int {
        var mask = (1 shl CosmoRunGame.NUM_LANES) - 1
        for (c in cells) {
            if (!c.type.solid) continue
            if (c.row < to && c.row + c.length > from) mask = mask and (1 shl c.lane).inv()
        }
        return mask
    }

    /** Les motifs, dans l'ordre d'écriture. Chargés une fois. */
    val all: List<Pattern> by lazy { defs.map { parse(it.name, it.tier, it.themes, it.weight, it.breather, it.grid) } }

    /** Le même motif vu dans un miroir : double le catalogue. */
    fun mirror(p: Pattern): Pattern {
        fun flip(mask: Int): Int {
            var out = 0
            for (l in 0 until CosmoRunGame.NUM_LANES) if (mask and (1 shl l) != 0) out = out or (1 shl (CosmoRunGame.NUM_LANES - 1 - l))
            return out
        }
        return Pattern(p.name, p.tier, p.themes, p.weight, p.rows,
            p.cells.map { Cell(CosmoRunGame.NUM_LANES - 1 - it.lane, it.row, it.length, it.type, it.roofed) },
            flip(p.entry), flip(p.exit), flip(p.exitRoof), p.breather)
    }


    init {
        // ── Respirations (palier 0) : des atomes, parfois un objet, rien qui blesse ─────────────────
        pattern("river", 0, breather = true, weight = 4, grid = """
            ..a..
            ..a..
            ..a..
            .a.a.
            a...a
            .a.a.
            ..a..
            ..a..
        """)
        pattern("gift", 0, breather = true, weight = 2, grid = """
            ..a..
            .a.a.
            a.s.a
            .a.a.
            ..a..
            ..a..
        """)
        pattern("wave", 0, breather = true, weight = 3, grid = """
            a....
            .a...
            ..a..
            ...a.
            ....a
            ...a.
            ..a..
            .a...
            a....
        """)
        pattern("magnet_run", 0, breather = true, weight = 1, grid = """
            ..m..
            ..a..
            .a.a.
            a...a
            .a.a.
            ..a..
            ..a..
        """)
        pattern("overdrive_run", 0, breather = true, weight = 1, grid = """
            ..b..
            ..a..
            ..a..
            ..a..
        """)

        // ── Palier 1 : une seule lecture à la fois ─────────────────────────────────────────────
        pattern("hurdle_wall", 1, grid = """
            hhhhh
            ..A..
            .AAA.
            ..A..
            .....
            .....
        """)
        pattern("gate_wall", 1, grid = """
            lllll
            .....
            .....
            ..a..
            ..a..
        """)
        pattern("pillars", 1, grid = """
            #.#.#
            .....
            .a.a.
            .....
            .#.#.
            .....
            a.a.a
            ..a..
        """)
        pattern("staggered_hurdles", 1, grid = """
            hh...
            .....
            .....
            ...hh
            .....
            .....
            hh...
            .....
            .a...
        """)

        // ── Palier 2 : combos et premiers dangers en hauteur ───────────────────────────────────
        pattern("jump_slide", 2, grid = """
            hhhhh
            ..A..
            .....
            .....
            .....
            lllll
            .....
            ..a..
            ..a..
        """)
        pattern("slide_jump", 2, grid = """
            lllll
            .....
            .....
            .....
            .....
            hhhhh
            ..A..
            .....
            ..a..
        """)
        pattern("drones", 2, themes = CRYSTAL or NEBULA, grid = """
            dd.dd
            .....
            .....
            .a.a.
            .....
            d.d.d
            .....
        """)
        pattern("stagger", 2, weight = 4, grid = """
            h.l.h
            .....
            .....
            l.h.l
            .....
            .....
            .a.a.
        """)
        pattern("slalom", 2, weight = 2, grid = """
            ###..
            .....
            .....
            .....
            ..###
            .....
            .....
            .....
            ###..
            .....
        """)
        pattern("first_roof", 2, weight = 4, grid = """
            h....
            .....
            /....
            /....
            #.h..
            @....
            @.a..
            #....
            #....
            .....
            .....
        """)
        pattern("loading_dock", 2, grid = """
            ../..
            ../..
            ..#h.
            ..@..
            ..@..
            ..#..
            ..@..
            .....
            .....
        """)

        // ── Palier 3 : il faut enchaîner ─────────────────────────────────────────────────────
        pattern("double_jump", 3, grid = """
            hhhh.
            .....
            .....
            .....
            .....
            .....
            .hhhh
            .....
            ..A..
        """)
        pattern("tunnel", 3, grid = """
            #.###
            #.###
            #l###
            #a###
            #a###
            .....
            .....
        """)
        pattern("zigzag", 3, weight = 2, grid = """
            ###..
            .....
            .....
            .....
            ..###
            .....
            .....
            .....
            ###..
            .....
            .....
        """)
        pattern("roof_run", 3, weight = 4, grid = """
            .....
            ./...
            ./...
            .#.h.
            .@...
            .^...
            .@...
            .#...
            .=...
            .#...
            .....
            .....
        """)
        pattern("mixed_gates", 3, grid = """
            hh.ll
            .....
            ..a..
            .....
            ll.hh
            .....
            ..a..
            .....
            .....
        """)

        // ── Palier 4 ─────────────────────────────────────────────────────────────────────────
        pattern("roof_gap", 4, weight = 4, grid = """
            .....
            ./...
            ./...
            .#...
            .@...
            .#...
            .....
            .....
            .#...
            .@...
            .#...
            .....
            .....
        """)
        pattern("chicane", 4, grid = """
            h.hhh
            .....
            .....
            .....
            .....
            lll.l
            .....
            .....
            .....
            hh.hh
            .....
            .....
        """)
        pattern("drone_slalom", 4, themes = NEBULA, grid = """
            dd.dd
            .....
            .....
            .....
            ..ddd
            .....
            .....
            .....
            ddd..
            .....
            .....
        """)
        pattern("roof_slalom", 4, grid = """
            .....
            /....
            /....
            #.h..
            @....
            #.l..
            #....
            #....
            .....
            .....
        """)


        // ── Toits : le chemin haut, plus riche en atomes, avec ses propres dangers ─────────────
        pattern("roof_bonus", 0, breather = true, weight = 2, grid = """
            .....
            ../..
            ../..
            ..#..
            ..@..
            ..#..
            ..@..
            ..#..
            ..@..
            ..#..
            .....
        """)
        pattern("sky_road", 3, weight = 3, grid = """
            ..h..
            .....
            ../..
            ../..
            ..#..
            ..@..
            ..^..
            ..#..
            .....
            ..#..
            ..@..
            ..#..
            ..=..
            ..#..
            ..#..
            ..@..
            ..#..
            ..^..
            ..#..
            .....
            .....
        """)
        pattern("roof_terrace", 3, weight = 3, grid = """
            .h...
            .....
            ./...
            ./...
            .##..
            .@#..
            .^@..
            .#^..
            .@#..
            .##..
            .....
        """)
        pattern("roof_hop", 4, weight = 3, grid = """
            .....
            ../..
            ../..
            ..#..
            ..@..
            ..#..
            .....
            .....
            ..#..
            ..@..
            ..#..
            .....
            .....
            ..#..
            ..@..
            ..#..
            .....
        """)
        pattern("ground_and_roof", 4, weight = 3, grid = """
            .....
            /...d
            /..d.
            #.d.d
            @....
            ^...l
            @....
            #....
            .....
        """)

        // ── Dangers propres aux mondes : les météores tombent sur la ceinture de cristal et la nébuleuse ───
        pattern("meteors", 2, themes = CRYSTAL or NEBULA, weight = 4, grid = """
            .*...
            .....
            ...*.
            .....
            *....
            .....
            ....*
            .....
            ..a..
        """)
        pattern("meteor_wall", 2, themes = CRYSTAL or NEBULA, weight = 3, grid = """
            **.**
            .....
            ..A..
            .....
            .....
            .**..
            .....
            ..a..
        """)
        pattern("meteor_storm", 4, themes = CRYSTAL or NEBULA, weight = 3, grid = """
            *.*.*
            .....
            .....
            .*.*.
            .....
            .....
            **.**
            .....
            .....
            ..*..
            .....
        """)
        pattern("meteor_roof", 4, themes = CRYSTAL or NEBULA, weight = 3, grid = """
            ..*..
            .....
            ../..
            ../..
            ..#..
            *.@.*
            ..#..
            ..=..
            ..#..
            .....
            .....
        """)

        // ── Palier 5 : la piste ne pardonne rien ─────────────────────────────────────────────
        pattern("gauntlet", 5, grid = """
            hhhh.
            .....
            .....
            .....
            .....
            .llll
            .....
            .....
            .....
            hhh.h
            .....
            .....
            .....
            .....
            l.lll
            .....
        """)
        pattern("storm", 5, weight = 1, grid = """
            ###..
            .....
            .....
            ..###
            .....
            .....
            ###..
            .....
            .....
            ..###
            .....
            .....
        """)
        pattern("tunnel_gates", 5, grid = """
            #.###
            #l###
            #a###
            #.###
            #l###
            #a###
            .....
            .....
        """)
    }
}
