package com.Atom2Universe.app.games.roguelike.demo

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Path

/** Gothique en pixel art : silhouette stable, cape articulée et ailes à racines fixes. */
internal object DungeonVampireSprites {
    private val vampire = """
        .........########...........
        ........#aqqqqaaa##.........
        .......#aqqaaaaaaa#.........
        .......#ahhhahhhmaa#........
        .......#hh##hm##maa#........
        .......#h#e#hm#e#ma#........
        ......#hhhhhmhhmmp#.........
        .......#hhmmmmmms#..........
        ........#h#w#wms#...........
        .........#hmmmss#...........
        ..........##hms#............
        ......##...#hms#...##.......
        ......#c###whmw###c#........
        .......#cccwGwwccc#.........
        ......#ddccwwwccddd#........
        .....#dds#cvwvvc#dds#.......
        .....#dds#cvGvvc#dds#.......
        ....#dds#.cvvvvc.#dds#......
        ....#dds#.cvGvvc.#dds#......
        ...#dds#..cvvvvc..#dds#.....
        ...#hms#..cvGvvc..#hms#.....
        ..#hhms#..cvvvvc..#hmss#....
        ...#hhs#..cGGGgc...#hms#....
        ....###...#vvvs#....###.....
        .........#vvvvvs#...........
        .........#vv#vvs#...........
        .........#vv#vvs#...........
        .........#vv#vvs#...........
        .........#vv#vvs#...........
        .........#ds#dds#...........
        .........#ds#dds#...........
        .........#ds#dds#...........
        ........#dds#dds#...........
        .......#ddds#ddds#..........
        ......#dddds#dddds#.........
        .......######.#####.........
    """.trimIndent()

    private val bat = """
        ....#....#.....
        ...#m#..#m#....
        ...#hm##mh#....
        ...#hmmmmms#...
        ..#hm#e#mmms#..
        .#phhmmmmmmms#.
        ..##w#wmmmss#..
        ....#mmmmss#...
        ....#hmmmss#...
        ....#hmmmss#...
        .....#mmss#....
        .....#mss#.....
        ....#w#.#w#....
        .....#...#.....
    """.trimIndent()

    fun create(style: DungeonDemoSprites.MonsterStyle, pose: Int = 0): Bitmap {
        val flying = style.isBat
        val bitmap = Bitmap.createBitmap(42, 36, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bitmap)
        val paint = Paint().apply { isAntiAlias = false }
        val outline = 0xFF111729.toInt()
        fun polygon(color: Int, vararg xy: Float) {
            val path = Path()
            path.moveTo(xy[0], xy[1])
            for (i in 2 until xy.size step 2) path.lineTo(xy[i], xy[i + 1])
            path.close()
            paint.color = color
            paint.style = Paint.Style.FILL
            canvas.drawPath(path, paint)
            paint.color = outline
            paint.style = Paint.Style.STROKE
            paint.strokeWidth = 1f
            canvas.drawPath(path, paint)
            paint.style = Paint.Style.FILL
        }
        val sway = intArrayOf(0, 1, 2, 1, 0, -1, -2, -1)[pose]
        if (flying) {
            // Le bout de l'aile monte et descend, le corps ne change jamais de hauteur.
            val tip = intArrayOf(5, 8, 14, 21, 25, 21, 14, 8)[pose].toFloat()
            polygon(style.skin.toInt(), 19f, 17f, 12f, 9f, 2f, tip,
                5f, tip + 7, 9f, tip + 5, 12f, tip + 10, 16f, 24f, 20f, 22f)
            polygon(style.skin.toInt(), 24f, 17f, 30f, 9f, 40f, tip,
                37f, tip + 7, 33f, tip + 5, 30f, tip + 10, 26f, 24f, 23f, 22f)
            paint.color = style.light.toInt()
            canvas.drawLine(19f, 17f, 2f, tip, paint)
            canvas.drawLine(24f, 17f, 40f, tip, paint)
        } else {
            polygon(style.shadow.toInt(), 13f, 12f, 26f, 12f,
                33f + sway, 33f, 26f, 31f, 20f, 34f, 13f, 31f, 7f + sway, 33f)
            polygon(style.skin.toInt(), 14f, 14f, 25f, 14f,
                29f + sway, 31f, 21f, 29f, 11f + sway, 31f)
        }
        val colors = mapOf('#' to outline, 'h' to style.light.toInt(), 'm' to style.fur.toInt(),
            's' to style.shadow.toInt(), 'c' to style.skin.toInt(), 'e' to style.eye.toInt(),
            'p' to 0xFFB07584.toInt(), 'w' to 0xFFF8E9D4.toInt(),
            'd' to 0xFF292838.toInt(), 'v' to 0xFF454052.toInt(),
            'a' to 0xFF252333.toInt(), 'q' to 0xFF57516D.toInt(),
            'G' to 0xFFDDBB76.toInt(), 'g' to 0xFF916D48.toInt())
        val rows = (if (flying) bat else vampire).lines()
        rows.forEachIndexed { y, row -> row.forEachIndexed pixel@ { x, ch ->
            paint.color = colors[ch] ?: return@pixel
            val arm = !flying && y in 16..22 && (x <= 7 || x >= 19)
            val dx = if (arm) sway * (y - 15) / 6 * (if (x < 12) 1 else -1) else 0
            val px = x + (if (flying) 14 else 6) + dx
            val py = y + if (flying) 10 else 0
            canvas.drawRect(px.toFloat(), py.toFloat(), px + 1f, py + 1f, paint)
        } }
        return bitmap
    }
}
