package com.Atom2Universe.app.games.roguelike.demo

import android.graphics.Bitmap
import android.graphics.Color
import com.Atom2Universe.app.games.roguelike.EquipSlot
import com.Atom2Universe.app.games.roguelike.Archetype

/** L'icône et la pièce portée partagent exactement le même dessin et la même palette. */
internal data class DemoGear(val slot: EquipSlot, val isotope: Boolean = false, val hue: Int = 210,
    val family: Archetype = Archetype.WARRIOR, val equipped: Boolean = true)

internal object DungeonDemoSprites {
    val slots = listOf(EquipSlot.HELMET, EquipSlot.CHEST, EquipSlot.BOOTS, EquipSlot.WEAPON, EquipSlot.OFFHAND)
    private val outline = 0xFF111729.toInt()
    fun metal(hue: Int) = intArrayOf(
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .44f, .34f)),
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .33f, .59f)),
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .19f, .85f))
    )
    fun equipment(item: DemoGear): Bitmap {
        val tones = metal(item.hue)
        val colors = mapOf('#' to outline, 's' to tones[0], 'm' to tones[1], 'h' to tones[2],
            'g' to 0xFFAF8654.toInt(), 'G' to 0xFFF0D59C.toInt(), 'r' to 0xFF86465A.toInt(),
            'd' to 0xFF492D45.toInt(), 'a' to 0xFF4B9EAA.toInt(), 'A' to 0xFFADF1DC.toInt(),
            'p' to 0xFFD5AA89.toInt(), 'e' to 0xFF342C37.toInt(), 'b' to 0xFF765344.toInt(),
            'w' to 0xFFE6DDC0.toInt(), 'v' to 0xFF25283F.toInt(), 'V' to 0xFF50536D.toInt())
        return pixels(if (!item.equipped) basePiece(item.slot) else if (item.family != Archetype.WARRIOR) DungeonClassSprites.source(item) else when (item.slot) {
            EquipSlot.HELMET -> if (item.isotope) HELMET_ISOTOPE else HELMET
            EquipSlot.CHEST -> if (item.isotope) CHEST_ISOTOPE else CHEST
            EquipSlot.BOOTS -> if (item.isotope) BOOTS_ISOTOPE else BOOTS
            EquipSlot.WEAPON -> if (item.isotope) SWORD_ISOTOPE else SWORD
            EquipSlot.OFFHAND -> if (item.isotope) SHIELD_ISOTOPE else SHIELD
            else -> error("Unsupported demo slot: ${item.slot}")
        }, colors)
    }
    // Tenue civile : mêmes points d'attache que les pièces de donjon.
    private fun basePiece(slot: EquipSlot) = when (slot) {
        EquipSlot.HELMET -> """
            .....######....
            ....#bbbbbb#...
            ...#bbbbbppp#..
            ...#bbbppppp#..
            ...#bppppepp#..
            ...#ppppppppp#.
            ....#ppppppp#..
            .....#ppppp#...
            ......#ppp#....
            ......#ppp#....
        """.trimIndent()
        EquipSlot.CHEST -> """
            .....#ppp#........
            ...###ppp###......
            ..#wwwwwwwww##....
            .#wwwwwwwwwwww#...
            .#wwwwwwwwwwww#...
            ..###wwwwww###....
            ....#wwwwww#......
            ....#wwwwww#......
            ....#wwwwww#......
            ....#wwwwww#......
            ....########......
            ....#ssssss#......
            ....#ss##ss#......
            ....###..###......
        """.trimIndent()
        EquipSlot.BOOTS -> """
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            .#ppp#...#ppp#...
            .#ppp#...#pppp#..
            .#####...######..
        """.trimIndent()
        else -> "."
    }
    // Même ancrage pour les deux variantes. Casque orienté vers la droite.
    private val HELMET = """
        ......####.....
        ....##hhmm##...
        ...#hhhmmmss#..
        ..#hhmmmmssss#.
        ..#hmmmmmmsss#.
        ..#mmmggggggg#.
        ..#mm#########.
        ..#mmshsssss#..
        ...#mss#s#ss#..
        ...#sss#s#s#...
        ....#ssssss#...
        .....######....
        ...............
    """
    private val HELMET_ISOTOPE = """
        .......#A#.....
        .....##aAm##...
        ...##hhAmmm##..
        ..#hhhmmmmsss#.
        .#ghmmmmmmmssg#
        .#gmmgGGGGGggg#
        ..#mm#########.
        ..#mmshsssss#..
        ..#gmss#s#ssg#.
        ...#gss#s#sg#..
        ....#gsssss#...
        .....#gggg#....
        ......####.....
    """
    private val CHEST = """
        ....#####.........
        ..##hhmmm##.......
        .#hhhmmmssm###....
        #hhmmmmssshhhm#...
        #hmmmmmssshmmm#...
        .#mmmmmmssmmss#...
        ..#hmmmmss####....
        ..#hmmmmsss#......
        ..#mmmmssss#......
        ..#mmssssss#......
        ..#ggggGggg#......
        ..#ssssssss#......
        ..#mmmmmmmm#......
        ...########.......
        ..................
    """
    private val CHEST_ISOTOPE = """
        ....#####.........
        ..##Ghhhh##.......
        .#Ghhmmmmmg###....
        #GhhmmmmssGhhm#...
        #ghmmmAmssgmmm#...
        .#gmmAaaAssgss#...
        ..#hmmaAmss###....
        ..#hmmmAmss#......
        ..#gmmmmssg#......
        ..#mgssssgs#......
        ..#gGggAGgg#......
        ..#ggssssgg#......
        ..#mmmmmmmm#......
        ...########.......
        ..................
    """
    // Jambes droites : deux pixels d'écart, pieds tournés dans le même sens.
    private val BOOTS = """
        .#####..#####....
        .#hmss#.#mmss#...
        .#hmss#.#mmss#...
        .#hmm##.#mmss#...
        .#mmss#.#msss#...
        .#mmss#.#msss#...
        .#hmmm#.#mmss##..
        .#hmmmm##mmmmm#..
        .##############..
    """
    private val BOOTS_ISOTOPE = """
        .#ggg#..#ggg#....
        .#hAms#.#mAss#...
        .#hmss#.#mmss#...
        .#hmm##.#mmss#...
        .#mgss#.#mgss#...
        .#mmss#.#msss#...
        .#hmmm#.#mmss##..
        .#hmmgg##mmmgg#..
        .##############..
    """
    private val SWORD = """
        .....#.....
        ....#h#....
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        .#..#hm#.#.
        .#gGgggGg#.
        ..###g###..
        ....#r#....
        ....#r#....
        ....#r#....
        ....#G#....
        .....#.....
    """
    private val SWORD_ISOTOPE = """
        .....#.....
        ....#A#....
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        .#..#Am#.#.
        .#GGgAgGG#.
        ..###g###..
        ....#r#....
        ....#r#....
        ....#r#....
        ....#A#....
        .....#.....
    """
    private val SHIELD = """
        ...#####.....
        .##gGGgg##...
        #ghmmmmssg#..
        #ghmmmmssg#..
        #gmmmGmssg#..
        #gmmGGGssg#..
        #gmmmGmssg#..
        #gmmmGmssg#..
        #gmmmmsssg#..
        .#gmmsssg#...
        .#gmmsssg#...
        ..#gsssg#....
        ...#gsg#.....
        ....###......
    """
    private val SHIELD_ISOTOPE = """
        ...##A##.....
        .##gGAGg##...
        #GhhmmmssG#..
        #ghmmAmssg#..
        #gmmAaAssg#..
        #gmAaaaAsg#..
        #gmmAaAssg#..
        #gmmmAmssg#..
        #gmmmmsssg#..
        .#GmmsssG#...
        .#gmmsssg#...
        ..#GsssG#....
        ...#GAG#.....
        ....###......
    """
    private val RAT = """
        .................................
        ........###......................
        .......#sps#..###................
        .......#sps###hpm#...............
        ........#mmhhhppm#...............
        .......#mmhhhhmmm#..######.......
        ......#mhhhhmmmmm##hhmmmm##......
        .....#mhmmmmmmmmhhhhmmmmmm#......
        ....#hhm#G#mmmmhhhhmmmmmmmm#.....
        ...#hhmm###mmmmmmmmmmmmmssmm#....
        ..#hhmmmmmmmmmmmmmmmmmsssssmm#...
        .#phhhmmmmmmmmmmmmmmsssssssmm#...
        ..###hhmmmmmmmmmmmsssssssssss#...
        .....##mmmmmmsssssssssssssss#...
        .......#hmmssssssssssmmsssss#....
        ........##sssssssss#mmmsss##.....
        .........#pss#.....#msss#........
        ........#ppp#......#ppp#.........
        .........###........###..........
    """
    internal enum class MonsterStyle(val shadow: Long, val fur: Long, val light: Long,
        val skin: Long, val eye: Long) {
        COMMON(0xFF51454F, 0xFF86746F, 0xFFB8A48D, 0xFFCF8C8B, 0xFFF2DAA8),
        GREY(0xFF343E50, 0xFF68788B, 0xFFA4B2BD, 0xFFA77F92, 0xFFEDD98A),
        BROWN(0xFF50352F, 0xFF956044, 0xFFD09A66, 0xFFC88A78, 0xFFFFD575),
        ALBINO(0xFF8E879A, 0xFFD2CCD0, 0xFFFFF0E1, 0xFFE3A0AA, 0xFFE74F69),
        BOSS(0xFF382F3B, 0xFF66515B, 0xFFC79B87, 0xFFB46A76, 0xFFFF674C),
        SKELETON(0xFF686979, 0xFFC3BDA4, 0xFFF0E5C4, 0xFF85644F, 0xFFFFB35D),
        SKELETON_MOSS(0xFF455C55, 0xFF91A88A, 0xFFD4D8AD, 0xFF52755B, 0xFFABE778),
        SKELETON_ASH(0xFF45455C, 0xFF858899, 0xFFCFCDDC, 0xFF686079, 0xFFFF785C),
        SKELETON_BOSS(0xFF615264, 0xFFBAAD98, 0xFFF4DFC0, 0xFF795262, 0xFFFF5429),
        ZOMBIE(0xFF43534A, 0xFF7B9570, 0xFFB0BC88, 0xFF91616B, 0xFFFFD57A),
        ZOMBIE_SWAMP(0xFF354F4D, 0xFF608E81, 0xFFA1BE91, 0xFF537849, 0xFFE7F589),
        ZOMBIE_PALE(0xFF5C5369, 0xFFA29AA7, 0xFFD0C4C5, 0xFF896079, 0xFFFFAA71),
        ZOMBIE_BOSS(0xFF525443, 0xFF93916D, 0xFFC7BA8A, 0xFF98707B, 0xFFFF733E),
        VAMPIRE(0xFF392D45, 0xFFB6A4AC, 0xFFE3D2CB, 0xFF984C65, 0xFFFF6757),
        VAMPIRE_NIGHT(0xFF292D47, 0xFFA5A6C1, 0xFFDDD8EA, 0xFF71619E, 0xFFFF9676),
        VAMPIRE_BAT(0xFF3D2C43, 0xFF826171, 0xFFBB9195, 0xFF925369, 0xFFFF6A4E),
        VAMPIRE_BAT_ASH(0xFF34344F, 0xFF767D9E, 0xFFB7BCD4, 0xFF75699A, 0xFFFFAB69);

        val isSkeleton get() = this == SKELETON || this == SKELETON_MOSS || this == SKELETON_ASH || this == SKELETON_BOSS
        val isZombie get() = this == ZOMBIE || this == ZOMBIE_SWAMP || this == ZOMBIE_PALE || this == ZOMBIE_BOSS
        val isHumanoid get() = isSkeleton || isZombie
        val isBat get() = this == VAMPIRE_BAT || this == VAMPIRE_BAT_ASH
        val isVampire get() = this == VAMPIRE || this == VAMPIRE_NIGHT || isBat
        val isBossAppearance get() = this == BOSS || this == SKELETON_BOSS || this == ZOMBIE_BOSS ||
            this == VAMPIRE || this == VAMPIRE_NIGHT
    }

    fun rat(style: MonsterStyle = MonsterStyle.COMMON): Bitmap {
        if (style.isSkeleton) return DungeonSkeletonSprites.create(style)
        if (style.isZombie) return DungeonZombieSprites.create(style)
        if (style.isVampire) return DungeonVampireSprites.create(style)
        val rows = RAT.trimIndent().lines().toMutableList()
        // Même corps de base ; les silhouettes de tête restent propres à chaque variété.
        when (style) {
            MonsterStyle.GREY -> rows[2] = ".......#sss#..###................"
            MonsterStyle.BROWN -> {
                rows[1] = "........####....................."
                rows[2] = ".......#spps#..###..............."
            }
            MonsterStyle.ALBINO -> rows[3] = ".......#ppp###hph#..............."
            MonsterStyle.BOSS -> {
                rows[0] = ".......####...####..............."
                rows[1] = "......#spps#.#spps#..............."
                rows[2] = "......#spps###hppmm#.............."
                rows[3] = ".....#hhhhhhhhmmss#..............."
                rows[4] = "....#hhhhhhhhmmmss#..............."
                rows[5] = "...#hhhhhhhmmmmss#..######........"
                rows[6] = "...#hhhhhmmmmms#..#hhmmmm##......."
                rows[7] = "..#hhh###hhmmms###hhhmmmmm#......."
                rows[8] = "..#hhh#G#hhmmmss#hhmmmmmmm#......."
                rows[9] = ".#hhhh###hhmmmss#mmmmmmmssmm#....."
                rows[10] = "#phhhhhhhhhmmmss#mmmmsssssmm#...."
                rows[11] = "#pphhhmmmhhhmmss#mmsssssssmm#...."
                rows[12] = ".#####ww#hhmmss#ssssssssssss#...."
                rows[13] = ".....#w#hmmmss#sssssssssssss#...."
                rows[14] = "......########ssssssmmsssss#....."
            }
            else -> Unit
        }
        return pixels(rows.joinToString("\n"), mapOf('#' to outline, 's' to style.shadow.toInt(),
            'm' to style.fur.toInt(), 'h' to style.light.toInt(), 'p' to style.skin.toInt(),
            'G' to style.eye.toInt(), 'w' to 0xFFF1DDBA.toInt()))
    }
    private fun pixels(source: String, colors: Map<Char, Int>): Bitmap {
        val rows = source.trimIndent().lines()
        val w = rows.maxOf { it.length }
        val data = IntArray(w * rows.size)
        rows.forEachIndexed { y, row -> row.forEachIndexed { x, ch -> data[y * w + x] = colors[ch] ?: 0 } }
        return Bitmap.createBitmap(data, w, rows.size, Bitmap.Config.ARGB_8888)
    }
}
