package com.Atom2Universe.app.games.roguelike.demo

import android.graphics.Bitmap
import android.graphics.Color
import com.Atom2Universe.app.games.roguelike.EquipSlot
import com.Atom2Universe.app.games.roguelike.Archetype

/** L'icône et la pièce portée partagent exactement le même dessin et la même palette. */
internal data class DemoGear(val slot: EquipSlot, val isotope: Boolean = false, val hue: Int = 210,
    val family: Archetype = Archetype.WARRIOR, val equipped: Boolean = true)

internal object DungeonDemoSprites {
    val slots = listOf(EquipSlot.HELMET, EquipSlot.CHEST, EquipSlot.BOOTS, EquipSlot.WEAPON, EquipSlot.OFFHAND)
    private val outline = 0xFF111729.toInt()
    fun metal(hue: Int) = intArrayOf(
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .44f, .34f)),
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .33f, .59f)),
        Color.HSVToColor(floatArrayOf(hue.toFloat(), .19f, .85f))
    )
    fun equipment(item: DemoGear): Bitmap {
        val tones = metal(item.hue)
        val colors = mapOf('#' to outline, 's' to tones[0], 'm' to tones[1], 'h' to tones[2],
            'g' to 0xFFAF8654.toInt(), 'G' to 0xFFF0D59C.toInt(), 'r' to 0xFF86465A.toInt(),
            'd' to 0xFF492D45.toInt(), 'a' to 0xFF4B9EAA.toInt(), 'A' to 0xFFADF1DC.toInt(),
            'p' to 0xFFD5AA89.toInt(), 'e' to 0xFF342C37.toInt(), 'b' to 0xFF765344.toInt(),
            'w' to 0xFFE6DDC0.toInt(), 'v' to 0xFF25283F.toInt(), 'V' to 0xFF50536D.toInt())
        return pixels(if (!item.equipped) basePiece(item.slot) else if (item.family != Archetype.WARRIOR) DungeonClassSprites.source(item) else when (item.slot) {
            EquipSlot.HELMET -> if (item.isotope) HELMET_ISOTOPE else HELMET
            EquipSlot.CHEST -> if (item.isotope) CHEST_ISOTOPE else CHEST
            EquipSlot.BOOTS -> if (item.isotope) BOOTS_ISOTOPE else BOOTS
            EquipSlot.WEAPON -> if (item.isotope) SWORD_ISOTOPE else SWORD
            EquipSlot.OFFHAND -> if (item.isotope) SHIELD_ISOTOPE else SHIELD
            else -> error("Unsupported demo slot: ${item.slot}")
        }, colors)
    }
    // Tenue civile : mêmes points d'attache que les pièces de donjon.
    private fun basePiece(slot: EquipSlot) = when (slot) {
        EquipSlot.HELMET -> """
            .....######....
            ....#bbbbbb#...
            ...#bbbbbppp#..
            ...#bbbppppp#..
            ...#bppppepp#..
            ...#ppppppppp#.
            ....#ppppppp#..
            .....#ppppp#...
            ......#ppp#....
            ......#ppp#....
        """.trimIndent()
        EquipSlot.CHEST -> """
            .....#ppp#........
            ...###ppp###......
            ..#wwwwwwwww##....
            .#wwwwwwwwwwww#...
            .#wwwwwwwwwwww#...
            ..###wwwwww###....
            ....#wwwwww#......
            ....#wwwwww#......
            ....#wwwwww#......
            ....#wwwwww#......
            ....########......
            ....#ssssss#......
            ....#ss##ss#......
            ....###..###......
        """.trimIndent()
        EquipSlot.BOOTS -> """
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            ..#pp#...#pp#....
            .#ppp#...#ppp#...
            .#ppp#...#pppp#..
            .#####...######..
        """.trimIndent()
        else -> "."
    }
    // Même ancrage pour les deux variantes. Casque orienté vers la droite.
    private val HELMET = """
        ......####.....
        ....##hhmm##...
        ...#hhhmmmss#..
        ..#hhmmmmssss#.
        ..#hmmmmmmsss#.
        ..#mmmggggggg#.
        ..#mm#########.
        ..#mmshsssss#..
        ...#mss#s#ss#..
        ...#sss#s#s#...
        ....#ssssss#...
        .....######....
        ...............
    """
    private val HELMET_ISOTOPE = """
        .......#A#.....
        .....##aAm##...
        ...##hhAmmm##..
        ..#hhhmmmmsss#.
        .#ghmmmmmmmssg#
        .#gmmgGGGGGggg#
        ..#mm#########.
        ..#mmshsssss#..
        ..#gmss#s#ssg#.
        ...#gss#s#sg#..
        ....#gsssss#...
        .....#gggg#....
        ......####.....
    """
    private val CHEST = """
        ....#####.........
        ..##hhmmm##.......
        .#hhhmmmssm###....
        #hhmmmmssshhhm#...
        #hmmmmmssshmmm#...
        .#mmmmmmssmmss#...
        ..#hmmmmss####....
        ..#hmmmmsss#......
        ..#mmmmssss#......
        ..#mmssssss#......
        ..#ggggGggg#......
        ..#ssssssss#......
        ..#mmmmmmmm#......
        ...########.......
        ..................
    """
    private val CHEST_ISOTOPE = """
        ....#####.........
        ..##Ghhhh##.......
        .#Ghhmmmmmg###....
        #GhhmmmmssGhhm#...
        #ghmmmAmssgmmm#...
        .#gmmAaaAssgss#...
        ..#hmmaAmss###....
        ..#hmmmAmss#......
        ..#gmmmmssg#......
        ..#mgssssgs#......
        ..#gGggAGgg#......
        ..#ggssssgg#......
        ..#mmmmmmmm#......
        ...########.......
        ..................
    """
    // Jambes droites : deux pixels d'écart, pieds tournés dans le même sens.
    private val BOOTS = """
        .#####..#####....
        .#hmss#.#mmss#...
        .#hmss#.#mmss#...
        .#hmm##.#mmss#...
        .#mmss#.#msss#...
        .#mmss#.#msss#...
        .#hmmm#.#mmss##..
        .#hmmmm##mmmmm#..
        .##############..
    """
    private val BOOTS_ISOTOPE = """
        .#ggg#..#ggg#....
        .#hAms#.#mAss#...
        .#hmss#.#mmss#...
        .#hmm##.#mmss#...
        .#mgss#.#mgss#...
        .#mmss#.#msss#...
        .#hmmm#.#mmss##..
        .#hmmgg##mmmgg#..
        .##############..
    """
    private val SWORD = """
        .....#.....
        ....#h#....
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        .#..#hm#.#.
        .#gGgggGg#.
        ..###g###..
        ....#r#....
        ....#r#....
        ....#r#....
        ....#G#....
        .....#.....
    """
    private val SWORD_ISOTOPE = """
        .....#.....
        ....#A#....
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        ...#hAm#...
        .#..#Am#.#.
        .#GGgAgGG#.
        ..###g###..
        ....#r#....
        ....#r#....
        ....#r#....
        ....#A#....
        .....#.....
    """
    private val SHIELD = """
        ...#####.....
        .##gGGgg##...
        #ghmmmmssg#..
        #ghmmmmssg#..
        #gmmmGmssg#..
        #gmmGGGssg#..
        #gmmmGmssg#..
        #gmmmGmssg#..
        #gmmmmsssg#..
        .#gmmsssg#...
        .#gmmsssg#...
        ..#gsssg#....
        ...#gsg#.....
        ....###......
    """
    private val SHIELD_ISOTOPE = """
        ...##A##.....
        .##gGAGg##...
        #GhhmmmssG#..
        #ghmmAmssg#..
        #gmmAaAssg#..
        #gmAaaaAsg#..
        #gmmAaAssg#..
        #gmmmAmssg#..
        #gmmmmsssg#..
        .#GmmsssG#...
        .#gmmsssg#...
        ..#GsssG#....
        ...#GAG#.....
        ....###......
    """
    private val RAT = """
        .................................
        ........###......................
        .......#sps#..###................
        .......#sps###hpm#...............
        ........#mmhhhppm#...............
        .......#mmhhhhmmm#..######.......
        ......#mhhhhmmmmm##hhmmmm##......
        .....#mhmmmmmmmmhhhhmmmmmm#......
        ....#hhm#G#mmmmhhhhmmmmmmmm#.....
        ...#hhmm###mmmmmmmmmmmmmssmm#....
        ..#hhmmmmmmmmmmmmmmmmmsssssmm#...
        .#phhhmmmmmmmmmmmmmmsssssssmm#...
        ..###hhmmmmmmmmmmmsssssssssss#...
        .....##mmmmmmsssssssssssssss#...
        .......#hmmssssssssssmmsssss#....
        ........##sssssssss#mmmsss##.....
        .........#pss#.....#msss#........
        ........#ppp#......#ppp#.........
        .........###........###..........
    """
    fun rat(): Bitmap = pixels(RAT, mapOf('#' to outline, 's' to 0xFF51454F.toInt(),
        'm' to 0xFF86746F.toInt(), 'h' to 0xFFB8A48D.toInt(),
        'p' to 0xFFCF8C8B.toInt(), 'G' to 0xFFF2DAA8.toInt()))
    private fun pixels(source: String, colors: Map<Char, Int>): Bitmap {
        val rows = source.trimIndent().lines()
        val w = rows.maxOf { it.length }
        val data = IntArray(w * rows.size)
        rows.forEachIndexed { y, row -> row.forEachIndexed { x, ch -> data[y * w + x] = colors[ch] ?: 0 } }
        return Bitmap.createBitmap(data, w, rows.size, Bitmap.Config.ARGB_8888)
    }
}
