package com.Atom2Universe.app.games.roguelike.demo

import android.graphics.Bitmap
import android.graphics.Color
import kotlin.random.Random

/** Poses articulées sur la grille : épaules fixes, mains pendantes et pas traînants. */
internal object DungeonZombieSprites {
    private val body = """
        .........######...........
        ........#ddddmm##.........
        .......#dddhhhhmm#........
        .......#dhhhhhhmmm#.......
        .......#hhhshhssmm#.......
        .......#hh#e#m#e#s#.......
        ......#hhhssmmssms#.......
        ......#hhhmssmmmms#.......
        .......#hhm###mmss#.......
        .......#hh#w#w#mss#.......
        ........#hmmmms##.........
        .........##hms#...........
        ......####hhms####........
        .....#ttttthmttttt#.......
        ....#ttttttsttttttt#......
        ...#hms#tttstttt#hms#.....
        ..#hhms#tttstttt#hms#.....
        ..#hms#.tttsttss#hmss#....
        .#hhms#.tttpptss#hmss#....
        .#hms#..ttppptss#hms#.....
        .#hms#..tttpptss#hms#.....
        #hhmss#.tttsttss.#hms#....
        #h#h#s#.tts#tss#.#hms#....
        .#####..#vvvsvv#.#hmms#...
        ........#vvvsvv#..#h#h#...
        ........#vv##vvv#..###....
        ........#vv#.#vv#.........
        ........#vv#.#vv#.........
        .......#hms#.#vvs#........
        .......#hmss#.#ms#........
        ........#hms#.#ms#........
        ........#hms#.#mss#.......
        ......##ddds#.#ddds#......
        .....#ddddds#.#dddds#.....
        ......#######..#####......
    """.trimIndent()

    // Une palette par apparition, réutilisée pour toutes les poses et le portrait.
    data class Clothes(val shirt: Int, val trousers: Int)

    fun randomClothes(rng: Random = Random): Clothes {
        val hue = rng.nextFloat() * 360f
        return Clothes(Color.HSVToColor(floatArrayOf(hue, .28f, .64f)),
            Color.HSVToColor(floatArrayOf((hue + 35f) % 360f, .24f, .40f)))
    }

    private val belly = """
        ........####hhms#####............
        .....###tttthmsttttttt###.........
        ....#tttttttstttttttttttt#........
        ...#hms#ttttstttttttt#hmss#.......
        ..#hhms#tttthhhhmmttt#hmmss#......
        ..#hms#ttthhhhhhhhmmtt#hmss#......
        .#hhms#tthhhhhhhhhhmmtt#hms#......
        .#hms#tthhhhhhhhhhhmmst#hms#......
        .#hms#thhhhhhhhhhhhmmmss#hms#.....
        #hhms#hhhhhhhhhhhhhmmmss#hms#.....
        #h#hs#hhhhhhhhhhhhmmmmss#hms#.....
        .####shhhhhhhhh#s#mmmmss#hmms#....
        .....#hhhhhhhhhsssmmmmss#h#h#.....
        .....#hhhhhhhhmmmmmmmmss#.###.....
        ......#hhhhhhmmmmmmmmss#..........
        .......#hmmmmmmmmmmmss#...........
        ........##ssssssssss#............
        .........#vvvvvvvvv#.............
        .........#vvvv#vvvv#.............
        .........#vvv#.#vvv#.............
        ........#hmss#.#hmss#............
        ........#hmss#..#hmss#...........
        ........#hmss#..#hmss#...........
        ........#hmss#..#hmss#...........
        ......##dddds#..#dddds#..........
        .....#dddddds#..#ddddds#.........
        ......########...######.........
    """.trimIndent()

    fun create(style: DungeonDemoSprites.MonsterStyle, pose: Int = 0, jaw: Int = 0,
        clothes: Clothes? = null): Bitmap {
        val boss = style == DungeonDemoSprites.MonsterStyle.ZOMBIE_BOSS
        val rows = if (boss) (body.lines().take(12).map { "...$it" } + belly.lines()).toMutableList()
            else body.lines().toMutableList()
        when (style) {
            DungeonDemoSprites.MonsterStyle.ZOMBIE_SWAMP -> {
                rows[0] = ".........##pp###.........."
                rows[1] = "........#ppphhmm##........"
                rows[2] = ".......#ppphhhhmm#........"
                rows[13] = ".....#ttttthmtttpp#......."
                rows[14] = "....#ttttttsttttppp#......"
                rows[18] = ".#hhms#.ttppppss#hmss#...."
            }
            DungeonDemoSprites.MonsterStyle.ZOMBIE_PALE -> {
                rows[0] = "..........#####..........."
                rows[1] = "........##hhhhh#.........."
                rows[2] = ".......#hhhhhhmm#........."
                rows[5] = ".......#hh#e#m###s#......."
                rows[6] = "......#hhhssmmpmms#......."
                rows[7] = "......#hhhmsspppms#......."
                rows[16] = "..#hhms#tttstt..#hms#....."
                rows[17] = "..#hms#.tttst...#hmss#...."
            }
            else -> Unit
        }
        val cloth = when (style) {
            DungeonDemoSprites.MonsterStyle.ZOMBIE_SWAMP -> 0xFF71634F.toInt()
            DungeonDemoSprites.MonsterStyle.ZOMBIE_PALE -> 0xFF655B87.toInt()
            else -> 0xFF7E5260.toInt()
        }
        val palette = mapOf('#' to 0xFF111729.toInt(), 'h' to style.light.toInt(),
            'm' to style.fur.toInt(), 's' to style.shadow.toInt(), 'p' to style.skin.toInt(),
            'e' to style.eye.toInt(), 't' to (clothes?.shirt ?: cloth),
            'v' to (clothes?.trousers ?: 0xFF354250.toInt()),
            'd' to 0xFF353137.toInt(), 'w' to 0xFFE3D5AB.toInt())
        val width = if (boss) 46 else 38
        val height = rows.size
        val pixels = IntArray(width * height)
        val drag = intArrayOf(0, 0, 1, 2, 1, 0, -1, -1)[pose]
        val reach = intArrayOf(0, 1, 2, 2, 1, 0, -1, 0)[pose]
        for (layer in 0..1) {
            rows.forEachIndexed { y, row -> row.forEachIndexed pixel@ { x, ch ->
                val color = palette[ch] ?: return@pixel
                val leftArm = y in 15..22 && x <= (if (boss) 4 else 6)
                val rightArm = y in 15..25 && x >= (if (boss) 26 else 17)
                val legStart = if (boss) 34 else 29
                val legCenter = if (boss) 16 else 12
                if ((leftArm || rightArm) != (layer == 0)) return@pixel
                // Le bras avant se tend lentement, l'autre pend avec un léger retard.
                val dx = when {
                    leftArm -> -reach * (y - 15) / 6
                    rightArm -> drag * (y - 15) / 8
                    y >= legStart && x <= legCenter -> if (pose in 2..4) -1 else 0
                    y >= legStart -> if (pose in 6..7) 1 else 0
                    else -> 0
                }
                val dy = when {
                    y in 9..10 -> jaw
                    leftArm -> -reach * (y - 15) / 8
                    y > legStart && x <= legCenter && pose == 3 -> -1
                    y > legStart && x > legCenter && pose == 7 -> -1
                    else -> 0
                }
                val px = x + 6 + dx
                val py = y + dy
                if (px in 0 until width && py in 0 until height) pixels[py * width + px] = color
            } }
        }
        for (y in 9 until 9 + jaw) for (x in 8..16) {
            pixels[y * width + x + 6 + (if (boss) 3 else 0)] =
                if (x == 8 || x == 16) style.shadow.toInt() else 0xFF111729.toInt()
        }
        // La scène applique déjà un miroir global : retourne aussi le dessin du zombie
        // pour que son profil regarde le héros, à droite dans l'image finale.
        val facingHero = IntArray(pixels.size)
        for (y in 0 until height) for (x in 0 until width) {
            facingHero[y * width + width - 1 - x] = pixels[y * width + x]
        }
        return Bitmap.createBitmap(facingHero, width, height, Bitmap.Config.ARGB_8888)
    }
}
