package com.Atom2Universe.app.games.roguelike.demo

import com.Atom2Universe.app.games.roguelike.Archetype
import com.Atom2Universe.app.games.roguelike.EquipSlot

/** Silhouettes de la démo : chaque famille possède cinq dessins, indépendants de leur teinte. */
internal object DungeonClassSprites {
    fun defaultHue(family: Archetype) = when (family) {
        Archetype.WARRIOR -> 210
        Archetype.ROGUE -> 155
        Archetype.MAGE -> 260
        Archetype.VAGABOND -> 35
        Archetype.NECROMANCER -> 185
    }

    fun offsetX(item: DemoGear) = when {
        item.family == Archetype.ROGUE && item.slot == EquipSlot.OFFHAND -> -6f
        item.family == Archetype.NECROMANCER && item.slot == EquipSlot.CHEST -> -6f
        item.family == Archetype.MAGE && item.slot == EquipSlot.HELMET -> -1f
        else -> 0f
    }
    fun offsetY(item: DemoGear) = when {
        item.family == Archetype.ROGUE && item.slot == EquipSlot.OFFHAND -> -2f
        item.family == Archetype.NECROMANCER && item.slot == EquipSlot.CHEST -> -6f
        item.family == Archetype.MAGE && item.slot == EquipSlot.HELMET -> -4f
        else -> 0f
    }

    fun source(item: DemoGear): String {
        val models = when (item.family) {
            Archetype.ROGUE -> rogue
            Archetype.MAGE -> mage
            Archetype.VAGABOND -> wanderer
            Archetype.NECROMANCER -> necromancer
            Archetype.WARRIOR -> error("Heavy pieces are defined in DungeonDemoSprites")
        }
        val rows = models[DungeonDemoSprites.slots.indexOf(item.slot)].trimIndent().lines().map { it.toCharArray() }
        if (!item.isotope) return rows.joinToString("\n") { String(it) }
        // Ornements propres aux sets : galons, broches et runes. Ni visage ni corbeau recolorés.
        fun put(x: Int, y: Int, value: Char) {
            val row = rows.getOrNull(y) ?: return
            if (x in row.indices && row[x] in "smhgbw") row[x] = value
        }
        when (item.slot) {
            EquipSlot.HELMET -> {
                val y = when (item.family) {
                    Archetype.MAGE -> 4
                    Archetype.ROGUE -> 2
                    else -> 4
                }
                put(7, y, 'A'); put(6, y + 1, 'g'); put(8, y + 1, 'g')
                if (item.family == Archetype.ROGUE) {
                    // Liseré sur le tissu extérieur, sans transformer le masque en visière dorée.
                    for (row in 4..9) put(3, row, 'g')
                } else {
                    for (x in 2..13) put(x, y + 3, if (x % 3 == 0) 'G' else 'g')
                }
            }
            EquipSlot.CHEST -> {
                val dx = if (item.family == Archetype.NECROMANCER) 6 else 0
                val dy = if (item.family == Archetype.NECROMANCER) 6 else 0
                put(dx + 8, dy + 4, 'A')
                put(dx + 7, dy + 5, 'a'); put(dx + 9, dy + 5, 'a')
                put(dx + 8, dy + 6, 'A')
                for (y in dy + 2 until rows.size - 1) {
                    put(dx + 3, y, 'g'); put(dx + 12, y, 'g')
                }
            }
            EquipSlot.BOOTS -> {
                for (x in 1..13) {
                    put(x, 1, 'g')
                    put(x, 5, 'g') // Brides dorées également visibles sur les sandales du mage.
                }
                put(3, 2, 'A'); put(10, 2, 'A')
            }
            EquipSlot.WEAPON -> {
                for (y in 1..12) put(5, y, if (y % 3 == 0) 'A' else 'a')
                put(5, 19, 'A')
            }
            EquipSlot.OFFHAND -> {
                for (y in 2..10) { put(2, y, 'g'); put(9, y, 'g') }
                put(6, 5, 'A'); put(5, 6, 'a'); put(7, 6, 'a'); put(6, 7, 'A')
            }
            else -> Unit
        }
        return rows.joinToString("\n") { String(it) }
    }

    // Capuche enveloppante et masque, gilet court à bandoulière, bottes souples, dague et arc.
    private val rogue = arrayOf("""
        .......##......
        .....##hm#.....
        ...##hhmmss#...
        ..#hhmmmssss#..
        ..#hmm###msss#.
        ..#hm#ppp#sss#.
        ..#hm#eppepss#.
        ..#hm#sssssss#.
        ..#mm#smssss#..
        ...#mm#ssss#...
        ...#hmm#ss#....
        ....#mmm##.....
        .....####......
    """, """
        ....#####.........
        ...#hhmmm##.......
        ..#hhgmmmss###....
        .#hmmgmmmssmmm#...
        .#hmmmgmmssmms#...
        ..#hmmmgmss###....
        ..#hmmmmGss#......
        ..#mmmmssgs#......
        ..#mmmssssg#......
        ..#ggggGggg#......
        ..#bsmmmmss#......
        ..#bbmmmmss#......
        ...###..###.......
        ..................
        ..................
    """, """
        .#####..####.....
        .#mmss#.#mss#....
        .#hhms#.#mms#....
        .#bbbs#.#bbs#....
        .#bmss#.#mss#....
        ..#mss#.#mss#....
        ..#bss#.#bss#....
        ..#bbbs##bbbb#...
        ..############...
    """, """
        ...........
        ...........
        ...........
        ...........
        ...........
        ...........
        .....#.....
        ....#h#....
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ....#hm#...
        ...#ghmg#..
        ...#gggg#..
        ....#g#....
        ....#b#....
        ....#b#....
        ....#b#....
        ....#G#....
        .....#.....
    """, """
        ##.....................##
        #gwwwwwwwwwwwwwwwwwwwwwg#
        .#b#.................#b#.
        ..#gb#.............#bg#..
        ...#gbb#.........#bbg#...
        .....#gbb#######bbg#.....
        .......#ggbbbbbgg#.......
        ........##bbgbb##........
        ..........#####..........
    """)

    // Chapeau compact, visage plus large sous le bord, robe en cloche, sandales, bâton et orbe.
    private val mage = arrayOf("""
        ........###......
        .......#hm#......
        ......#hmm#......
        .....#hmmm#......
        .....#hmmss#.....
        ....#hGmmsss#....
        ....#hmGmsss#....
        ...#ggggggggg#...
        ..#hhmmmmmmsss#..
        .###############.
        ....#ppppppps#...
        ....#ppppppps#...
        ....#ppeppeps#...
        ....#ppppppps#...
        .....#ppppps#....
        ......#ppps#.....
        .......####......
    """, """
        ....#####.........
        ..##hggmm##.......
        .#hhmmgmmss###....
        #hhmmmgmmssmmm#...
        #hmmmmgmmssmms#...
        #hmmmmGmmssmms#...
        .##mmmgmmss###....
        ...#mmgmmss#......
        ...#mmgmmss#......
        ..#ggggGgggg#.....
        ..#hmmgmmsms#.....
        ..#hmmgmmsmss#....
        ..#hmmgmmssms#....
        .#hhmmgmmssmss#...
        .#hmmmgmmssmss#...
        .#hmmmgmmssmmss#..
        #hhmmmgmmsssmmss#.
        #hmmmmgmmsssmmss#.
        #ggggggggggggggg#.
        .###############..
    """, """
        ..####..####.....
        ..#pps..#pps#....
        ..#pps#.#pps#....
        ..#pps#.#pps#....
        ..#pps#.#pps#....
        ..#bbs#.#bbs#....
        ..#pps#.#pps#....
        ..#bppp##bppp#...
        ..############...
    """, """
        ....###....
        ...#gAg#...
        ..#gAaAg#..
        ..#gAaAg#..
        ...#gAg#...
        ....#g#....
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#gb#...
        ....#gb#...
        ....#bb#...
        ....#bb#...
        ....#bb#...
        ....#gb#...
        .....##....
    """, """
        .............
        ....####.....
        ..##hAaa##...
        .#hAAaaaam#..
        .#hAaaaamm#..
        #hAaaaammms#.
        #aaaaammmss#.
        .#aammmmss#..
        .#mmmmmsss#..
        ..##msss##...
        ...#gggg#....
        ....#gg#.....
        .....##......
        .............
    """)

    // Coiffe à plume, manteau fendu à sacoche, guêtres, hache et lanterne.
    private val wanderer = arrayOf("""
        ...........#w#.
        ..........#ww#.
        .....#####ww#..
        ...##hmmm#w#...
        ..#hhmmmmss#...
        ..#hmmmmsss#...
        .#gggggggggg#..
        ..###ppppps##..
        ...#ppepeps#...
        ...#pppppps#...
        ....#pppps#....
        .....#pps#.....
        ......###......
    """, """
        ....#####.........
        ..##wggww##.......
        .#wwmmmmmww###....
        #wwhmmmmmsswmm#...
        #hmmmmmmmssmms#...
        .#mmmGmmmss###....
        ..#hmmmmsss#......
        ..#hmmmmsss###....
        ..#hmmmmssgbbb#...
        ..#gggggggbGb#...
        ..#hmmbmssgbb#...
        ..#hmmbmsss###...
        ..#hmmbmsss#......
        ..#hmm#mmsss#.....
        ..#hmm#mmsss#.....
        .#hmm#.#mmsss#....
        .#hmm#.#mmsss#....
        .#gmm#..#mmsg#....
        ..###....####.....
    """, """
        .#ggg#..#ggg#....
        .#bmss#.#bss#....
        .#hhms#.#mms#....
        .#bmss#.#bss#....
        .#ggss#.#ggs#....
        .#bmss#.#bss#....
        .#bmss#.#bss##...
        .#bbbb###bbbb#...
        .#############...
    """, """
        ....#...##.
        ...#h#.#hm#
        ..#hhg#hmms
        .#hhmgmmmss
        .#hmmgbmmss
        ..#ssgbmss#
        ...##gb###.
        ....#gb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#hb#...
        ....#gb#...
        ....#gb#...
        ....#bb#...
        ....#bb#...
        ....#bb#...
        ....#gb#...
        .....##....
    """, """
        ....####.....
        ...#g..g#....
        ...#g..g#....
        ....#gg#.....
        ..##gggg##...
        .#gggggggg#..
        .#gwGGGwgg#..
        .#gwGGGwgg#..
        .#gwGGGwgg#..
        .#gwGGGwgg#..
        .#gggggggg#..
        ..#gggggg#...
        ...######....
        .............
    """)

    // Voile et masque d'os ; le corbeau fait partie de la toge (et donc de son icône).
    private val necromancer = arrayOf("""
        ......###......
        .....#hms#.....
        ....#hmmss#....
        ...#hhmmsss#...
        ..#hmmmwmsss#..
        ..#hmmwwwmss#..
        ..#mmwewewss#..
        ..#mmwwwwwss#..
        ..#mssw#wsss#..
        ..#mmsssssss#..
        ..#mssssssss#..
        ...#ss##sss#...
        ....##..###....
    """, """
        .....###................
        ....#vAv#...............
        ....#vvvg#..............
        ...#VVvv#...............
        ...#Vvvvv#..............
        ....#vvv#...............
        .....gg######...........
        ......##wmmww##.........
        .......#wwmmmmww###.....
        ......#whmmmmmsswmm#....
        ......#hmmmmwmssmms#....
        .......#mmmwwwss###.....
        ........#mmmwmss#.......
        ........#hmmwmss#.......
        ........#hmmwmss#.......
        ........#wwwwwww#.......
        ........#hmsmmss#.......
        .......#hhmsmmsss#......
        .......#hmmsmmsss#......
        .......#hmmsmmsss#......
        ......#hhmmssmmsss#.....
        ......#hmmsssmmsss#.....
        ......#hmms#smms#s#.....
        .......#ms#.#ms#.#......
        ........##...##.........
    """, """
        ..####..####.....
        ..#mss#.#mss#....
        ..#wws#.#wws#....
        ..#mss#.#mss#....
        ..#wws#.#wws#....
        ..#mss#.#mss#....
        ..#wws#.#wws#....
        ..#mmm###mmmm#...
        ..############...
    """, """
        ....###....
        ...#wAw#...
        ..#wwwww#..
        ..#wewew#..
        ...#www#...
        ....#w#....
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#ms#...
        ....#gs#...
        ....#gs#...
        ....#ss#...
        ....#ss#...
        ....#ss#...
        ....#As#...
        .....##....
    """, """
        .............
        ..########...
        .#ggggggg##..
        .#gmmmmmgw#..
        .#gmmwmmgw#..
        .#gmwwwmgw#..
        .#gmwewmgw#..
        .#gmmwmmgw#..
        .#gmmmmmgw#..
        .#gggggggw#..
        ..#wwwwwww#..
        ...########..
        .............
        .............
    """)
}
