package com.Atom2Universe.app.science.timeline

import androidx.annotation.StringRes
import com.Atom2Universe.app.R
import com.Atom2Universe.app.science.timeline.HumanHistory.ago
import com.Atom2Universe.app.science.timeline.HumanHistory.bce
import com.Atom2Universe.app.science.timeline.HumanHistory.ce

/** References checked in October 2026. Texts are original EN/FR summaries, no imported media. */
enum class HumanSource(@param:StringRes val label: Int, val url: String) {
    SAPIENS(R.string.ct_history_source_sapiens, "https://humanorigins.si.edu/evidence/human-fossils/species/homo-sapiens"),
    SAHUL(R.string.ct_history_source_sahul, "https://aws-digital-classroom.nma.gov.au/learning-modules/1/migration-sahul"),
    CATAL(R.string.ct_history_source_catal, "https://whc.unesco.org/en/list/1405"),
    URUK(R.string.ct_history_source_uruk, "https://www.getty.edu/art/exhibitions/mesopotamia/explore.html"),
    DHOLAVIRA(R.string.ct_history_source_dholavira, "https://whc.unesco.org/en/list/1645"),
    CARAL(R.string.ct_history_source_caral, "https://whc.unesco.org/en/list/1269/"),
    OLDKINGDOM(R.string.ct_history_source_oldkingdom, "https://www.metmuseum.org/ru/essays/egypt-in-the-old-kingdom-ca-2649-2150-b-c"),
    SHANG(R.string.ct_history_source_shang, "https://www.metmuseum.org/es/essays/shang-and-zhou-dynasties-the-bronze-age-of-china"),
    HAN(R.string.ct_history_source_han, "https://www.metmuseum.org/it/essays/han-dynasty-206-b-c-220-a-d"),
    ROME(R.string.ct_history_source_rome, "https://www.metmuseum.org/pt/essays/the-roman-empire-27-b-c-393-a-d"),
    MAYA(R.string.ct_history_source_maya, "https://www.metmuseum.org/ja/exhibitions/arts-of-the-ancient-americas/inside-the-exhibition"),
    TANG(R.string.ct_history_source_tang, "https://www.metmuseum.org/it/essays/tang-dynasty-618-906"),
    UMAYYADS(R.string.ct_history_source_umayyads, "https://www.metmuseum.org/ja/essays/the-art-of-the-umayyad-period-661-750"),
    ANGKOR(R.string.ct_history_source_angkor, "https://whc.unesco.org/en/list/668/"),
    ZIMBABWE(R.string.ct_history_source_zimbabwe, "https://whc.unesco.org/en/list/364/"),
    MAORI(R.string.ct_history_source_maori, "https://teara.govt.nz/en/history/page-1"),
    MANSA(R.string.ct_history_source_mansa, "https://www.metmuseum.org/exhibitions/sahel-art-empire-sahara/inside-the-exhibition"),
    SLAVE_TRADE(R.string.ct_history_source_slave_trade, "https://legacy.slavevoyages.org/assessment/estimates"),
    STEAM(R.string.ct_history_source_steam, "https://blog.sciencemuseum.org.uk/steaming-through-the-centuries/"),
    US_INDEPENDENCE(R.string.ct_history_source_us_independence, "https://www.archives.gov/milestone-documents/declaration-of-independence"),
    FRENCH_RIGHTS(R.string.ct_history_source_french_rights, "https://www.assemblee-nationale.fr/dyn/histoire-et-patrimoine/revolution-francaise/la-declaration-des-droits-de-l-homme-et-du-citoyen"),
    HAITI(R.string.ct_history_source_haiti, "https://whc.unesco.org/en/list/180/"),
    MEIJI(R.string.ct_history_source_meiji, "https://artmuseum.princeton.edu/object-package/becoming-modern-becoming-global-japanese-prints-meiji-period-1868-1912/35688"),
    WW1(R.string.ct_history_source_ww1, "https://www.iwm.org.uk/history/first-world-war"),
    WW2(R.string.ct_history_source_ww2, "https://main.ushmm.org/learn/holocaust/world-war-ii-and-the-holocaust-1939-1945"),
    HOLOCAUST(R.string.ct_history_source_holocaust, "https://encyclopedia.ushmm.org/content/en/article/introduction-to-the-holocaust?parent=en%2F28"),
    UN(R.string.ct_history_source_un, "https://www.un.org/en/about-us/history-of-the-un"),
    PARTITION(R.string.ct_history_source_partition, "https://www.nationalarchives.gov.uk/education/teaching-resources/partition-of-british-india/"),
    UDHR(R.string.ct_history_source_udhr, "https://www.un.org/en/about-us/universal-declaration-of-human-rights"),
    DECOLONIZATION(R.string.ct_history_source_decolonization, "https://www.un.org/en/global-issues/decolonization"),
    APOLLO(R.string.ct_history_source_apollo, "https://www.nasa.gov/wp-content/uploads/static/history/ap11ann/ap11events.html"),
    WEB(R.string.ct_history_source_web, "https://home.cern/science/computing/the-birth-of-the-web/"),
    SOUTH_AFRICA(R.string.ct_history_source_south_africa, "https://www.gov.za/issues/20years/milestones-20-years-freedom"),
    PARIS(R.string.ct_history_source_paris, "https://unfccc.int/news/bringing-the-paris-agreement-into-force"),
    EGYPT_OVERVIEW(R.string.ct_history_source_egypt_overview, "https://nmec.gov.eg/historical-timeline/"),
    MIDDLEKINGDOM(R.string.ct_history_source_middlekingdom, "https://www.metmuseum.org/essays/egypt-in-the-middle-kingdom-2030-1640-b-c"),
    NEWKINGDOM(R.string.ct_history_source_newkingdom, "https://www.metmuseum.org/essays/egypt-in-the-new-kingdom-ca-1550-1070-b-c"),
    LATEEGYPT(R.string.ct_history_source_lateegypt, "https://www.metmuseum.org/essays/egypt-in-the-late-period-ca-712-332-b-c"),
    HELLENISTIC_EGYPT(R.string.ct_history_source_hellenistic_egypt, "https://www.metmuseum.org/essays/egypt-in-the-ptolemaic-period"),
    ROMAN_EGYPT(R.string.ct_history_source_roman_egypt, "https://www.metmuseum.org/essays/roman-egypt"),
    KHUFU(R.string.ct_history_source_khufu, "https://egymonuments.gov.eg/monuments/the-great-pyramid/"),
    STONEHENGE(R.string.ct_history_source_stonehenge, "https://www.english-heritage.org.uk/visit/places/stonehenge/history-and-stories/"),
    PARTHENON(R.string.ct_history_source_parthenon, "https://www.theacropolismuseum.gr/en/exhibit-halls/parthenon-gallery"),
    COLOSSEUM(R.string.ct_history_source_colosseum, "https://www.turismoroma.it/en/node/1155"),
    HAGIA_SOPHIA(R.string.ct_history_source_hagia_sophia, "https://www.metmuseum.org/essays/hagia-sophia-532-37"),
    BOROBUDUR(R.string.ct_history_source_borobudur, "https://whc.unesco.org/en/list/592/"),
    NOTRE_DAME(R.string.ct_history_source_notre_dame, "https://notre-dame-de-paris.culture.gouv.fr/fr/le-monument"),
    MACHU_PICCHU(R.string.ct_history_source_machu_picchu, "https://whc.unesco.org/en/list/274/"),
    FORBIDDEN_CITY(R.string.ct_history_source_forbidden_city, "https://whc.unesco.org/en/list/439/"),
    TAJ_MAHAL(R.string.ct_history_source_taj_mahal, "https://whc.unesco.org/en/list/252/"),
    EIFFEL(R.string.ct_history_source_eiffel, "https://www.toureiffel.paris/en/the-monument/history"),
    SYDNEY_OPERA(R.string.ct_history_source_sydney_opera, "https://www.sydneyoperahouse.com/our-story"),
    KADESH(R.string.ct_history_source_kadesh, "https://www.britishmuseum.org/collection/term/x13949"),
    HASTINGS(R.string.ct_history_source_hastings, "https://www.english-heritage.org.uk/visit/places/1066-battle-of-hastings-abbey-and-battlefield/history-and-stories/what-happened-battle-hastings"),
    HUNDRED_YEARS(R.string.ct_history_source_hundred_years, "https://essentiels.bnf.fr/fr/article/6e6e48ab-6af5-4e58-8167-e2914a0b0098-guerre-cent-ans"),
    WATERLOO(R.string.ct_history_source_waterloo, "https://www.nam.ac.uk/explore/battle-waterloo"),
    US_CIVIL_WAR(R.string.ct_history_source_us_civil_war, "https://www.nps.gov/civilwar/overview.htm"),
    VERDUN(R.string.ct_history_source_verdun, "https://memorial-verdun.fr/fr/ressources/la-bataille-de-verdun"),
    SOMME(R.string.ct_history_source_somme, "https://www.iwm.org.uk/history/first-world-war/somme"),
    KOREA(R.string.ct_history_source_korea, "https://www.iwm.org.uk/history/cold-war/korean-war"),
    SCI_RHIND(R.string.ct_science_rhind_source, "https://www.britishmuseum.org/collection/object/Y_EA10057"),
    SCI_EUCLID(R.string.ct_science_euclid_source, "https://wwws.loc.gov/exhibits/vatican/math.html"),
    SCI_LIU_HUI(R.string.ct_science_liu_hui_source, "https://mathshistory.st-andrews.ac.uk/HistTopics/Nine_chapters/"),
    SCI_ARYABHATA(R.string.ct_science_aryabhata_source, "https://mathshistory.st-andrews.ac.uk/Biographies/Aryabhata_I/"),
    SCI_BRAHMAGUPTA(R.string.ct_science_brahmagupta_source, "https://mathshistory.st-andrews.ac.uk/Biographies/Brahmagupta/"),
    SCI_ALGEBRA(R.string.ct_science_algebra_source, "https://mathshistory.st-andrews.ac.uk/Biographies/Al-Khwarizmi/"),
    SCI_BHASKARA(R.string.ct_science_bhaskara_source, "https://mathshistory.st-andrews.ac.uk/BEA/bhaskara_ii_bea.pdf"),
    SCI_CALCULUS(R.string.ct_science_calculus_source, "https://mathshistory.st-andrews.ac.uk/Chronology/12/"),
    SCI_NOETHER(R.string.ct_science_noether_source, "https://arxiv.org/abs/physics/0503066"),
    SCI_OPTICS(R.string.ct_science_optics_source, "https://courier.unesco.org/en/articles/ibn-al-haythams-scientific-method"),
    SCI_NEWTON(R.string.ct_science_newton_source, "https://catalogues.royalsociety.org/CalmView/Record.aspx?id=18577&src=CalmView.CatalogL"),
    SCI_VOLTA(R.string.ct_science_volta_source, "https://makingscience.royalsociety.org/items/l-and-p_11_137/letter-account-of-electricity-excited-by-contact-and-conducting-substances-of-different-kinds-from-alessandro-volta-to-joseph-banks"),
    SCI_FARADAY(R.string.ct_science_faraday_source, "https://www.rigb.org/explore-science/explore/collection/michael-faradays-ring-coil-apparatus"),
    SCI_MAXWELL(R.string.ct_science_maxwell_source, "https://catalogues.royalsociety.org/CalmView/Record.aspx?id=PT%2F72%2F7&src=CalmView.Catalog"),
    SCI_XRAY(R.string.ct_science_xray_source, "https://www.aps.org/apsnews/2001/11/1895-roentgens-discovery-xrays"),
    SCI_BECQUEREL(R.string.ct_science_becquerel_source, "https://www.nobelprize.org/prizes/physics/1903/becquerel/biographical/?print=1"),
    SCI_ELECTRON(R.string.ct_science_electron_source, "https://educationalgames.nobelprize.org/educational/physics/vacuum/experiment-1.html"),
    SCI_PLANCK(R.string.ct_science_planck_source, "https://www.nobelprize.org/prizes/physics/1918/planck/biographical/?print=1"),
    SCI_RELATIVITY(R.string.ct_science_relativity_source, "https://educationalgames.nobelprize.org/educational/physics/relativity/history-1.html"),
    SCI_GENERAL_RELATIVITY(R.string.ct_science_general_relativity_source, "https://www.einstein-online.info/en/about-einstein-online/about-albert-einstein/"),
    SCI_NUCLEUS(R.string.ct_science_nucleus_source, "https://www.nobelprize.org/prizes/physics/1990/9592-the-nobel-prize-in-physics-1990/"),
    SCI_QUANTUM(R.string.ct_science_quantum_source, "https://www.nobelprize.org/prizes/themes/the-nobel-prize-in-physics-1901-2000/"),
    SCI_RAMAN(R.string.ct_science_raman_source, "https://www.nobelprize.org/prizes/physics/1930/raman/biographical/?print=1"),
    SCI_NEUTRON(R.string.ct_science_neutron_source, "https://www.nobelprize.org/laureate/41"),
    SCI_FISSION(R.string.ct_science_fission_source, "https://www.iaea.org/sites/default/files/publications/magazines/bulletin/bull4-0/04004790608su.pdf"),
    SCI_LASER(R.string.ct_science_laser_source, "https://www.aps.org/apsnews/2010/05/physics-history"),
    SCI_HIGGS(R.string.ct_science_higgs_source, "https://home.cern/cern-experiments-observe-particle-consistent-with-long-sought-higgs-boson/"),
    SCI_COPERNICUS(R.string.ct_science_copernicus_source, "https://www.loc.gov/resource/rbc0001.2012gen31925/?sp=2"),
    SCI_KEPLER(R.string.ct_science_kepler_source, "https://www.grc.nasa.gov/www/K-12/Aero2000/studweb/glossary/kepler.html"),
    SCI_GALILEO(R.string.ct_science_galileo_source, "https://www.nasa.gov/history/410-years-ago-galileo-discovers-jupiters-moons/"),
    SCI_LEAVITT(R.string.ct_science_leavitt_source, "https://platestacks.cfa.harvard.edu/henrietta-swan-leavitt/variable-stars"),
    SCI_PAYNE(R.string.ct_science_payne_source, "https://library.cfa.harvard.edu/cecilia-payne-gaposchkin/education-and-doctoral-thesis"),
    SCI_LEMAITRE(R.string.ct_science_lemaitre_source, "https://ntrs.nasa.gov/citations/20150000171"),
    SCI_HUBBLE(R.string.ct_science_hubble_source, "https://science.nasa.gov/missions/hubble/nasa-celebrates-edwin-hubbles-discovery-of-a-new-universe/"),
    SCI_SPUTNIK(R.string.ct_science_sputnik_source, "https://www.nasa.gov/wp-content/uploads/static/history/sputnik.html"),
    SCI_GAGARIN(R.string.ct_science_gagarin_source, "https://science.nasa.gov/resource/yuri-gagarin-first-human-in-space/"),
    SCI_CMB(R.string.ct_science_cmb_source, "https://lambda.gsfc.nasa.gov/resources/lambda_graphics/cmb_discovery.html"),
    SCI_PULSAR(R.string.ct_science_pulsar_source, "https://www.cam.ac.uk/stories/journeysofdiscovery-pulsars"),
    SCI_EXOPLANET(R.string.ct_science_exoplanet_source, "https://www.hq.eso.org/public/announcements/ann19049/"),
    SCI_GRAVITATIONAL_WAVES(R.string.ct_science_gravitational_waves_source, "https://www.ligo.caltech.edu/MIT/news/ligo20160914"),
    SCI_BLACK_HOLE_IMAGE(R.string.ct_science_black_hole_image_source, "https://www.eso.org/public/images/eso1907a/"),
    SCI_LAVOISIER(R.string.ct_science_lavoisier_source, "https://www.acs.org/education/whatischemistry/landmarks/lavoisier.html"),
    SCI_DALTON(R.string.ct_science_dalton_source, "https://www.sciencehistory.org/stories/magazine/john-dalton-and-the-scientific-method/"),
    SCI_PERIODIC_TABLE(R.string.ct_science_periodic_table_source, "https://periodic-table.rsc.org/about"),
    SCI_CURIE(R.string.ct_science_curie_source, "https://www.nobelprize.org/prizes/themes/marie-and-pierre-curie-and-the-discovery-of-polonium-and-radium/"),
    SCI_AMMONIA(R.string.ct_science_ammonia_source, "https://www.basf.com/es/es/who-we-are/historia/chronology/1902-1924/1913"),
    SCI_FULLERENE(R.string.ct_science_fullerene_source, "https://www.acs.org/education/whatischemistry/landmarks/fullerenes.html"),
    SCI_HOOKE(R.string.ct_science_hooke_source, "https://royalsociety.org/about-us/who-we-are/history/"),
    SCI_LEEUWENHOEK(R.string.ct_science_leeuwenhoek_source, "https://makingscience.royalsociety.org/items/el_l1_22/letter-from-antoni-van-leeuwenhoek-to-henry-oldenburg-dated-at-delft"),
    SCI_LINNAEUS(R.string.ct_science_linnaeus_source, "https://www.linnean.org/news/2023/09/06/species-plantarum-at-270"),
    SCI_SELECTION(R.string.ct_science_selection_source, "https://www.darwinproject.ac.uk/letters/darwins-life-letters/darwin-letters-1858-1859-origin"),
    SCI_MENDEL(R.string.ct_science_mendel_source, "https://mendelmuseum.muni.cz/en/about-the-museum/gregor-johann-mendel"),
    SCI_AVERY(R.string.ct_science_avery_source, "https://www.genome.gov/25520250/online-education-kit-1944-dna-is-transforming-principle"),
    SCI_DNA(R.string.ct_science_dna_source, "https://www.genome.gov/25520255/online-education-kit-1953-dna-double-helix"),
    SCI_SEQUENCING(R.string.ct_science_sequencing_source, "https://www.genome.gov/25520304/online-education-kit-197577-dna-sequencing"),
    SCI_PCR(R.string.ct_science_pcr_source, "https://www.genome.gov/25520323/online-education-kit-1983-pcr-invented"),
    SCI_HUMAN_GENOME(R.string.ct_science_human_genome_source, "https://www.genome.gov/about-genomics/educational-resources/fact-sheets/human-genome-project"),
    SCI_CRISPR(R.string.ct_science_crispr_source, "https://news.berkeley.edu/2019/06/25/crispr-timeline/"),
    SCI_T2T(R.string.ct_science_t2t_source, "https://pmc.ncbi.nlm.nih.gov/articles/PMC9186530/"),
    SCI_VESALIUS(R.string.ct_science_vesalius_source, "https://www.loc.gov/item/2021667096"),
    SCI_HARVEY(R.string.ct_science_harvey_source, "https://history.rcp.ac.uk/exhibitions/past-exhibitions/ceaseless-motion-experimentations-circulation"),
    SCI_JENNER(R.string.ct_science_jenner_source, "https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination"),
    SCI_SEMMELWEIS(R.string.ct_science_semmelweis_source, "https://semmelweis.hu/english/about-semmelweis-university/semmelweis200/"),
    SCI_SNOW(R.string.ct_science_snow_source, "https://www.lshtm.ac.uk/newsevents/news/2019/john-snow-memorial-pump-marking-historic-cholera-outbreak-reinstalled-its"),
    SCI_RABIES(R.string.ct_science_rabies_source, "https://www.pasteur.fr/fr/nous-connaitre/du-vaccin-contre-la-rage-la-creation-de-linstitut"),
    SCI_INSULIN(R.string.ct_science_insulin_source, "https://magazine.utoronto.ca/campus/history/history-of-insulin-banting-best-macleod-collip/"),
    SCI_PENICILLIN(R.string.ct_science_penicillin_source, "https://www.acs.org/education/whatischemistry/landmarks/flemingpenicillin.html"),
    SCI_ARTEMISININ(R.string.ct_science_artemisinin_source, "https://www.nobelprize.org/prizes/medicine/2015/tu/biographical/"),
    SCI_SMALLPOX(R.string.ct_science_smallpox_source, "https://www.who.int/news-room/detail/08-05-2020-commemorating-smallpox-eradication-a-legacy-of-hope-for-covid-19-and-other-diseases"),
    SCI_STENO(R.string.ct_science_steno_source, "https://ucmp.berkeley.edu/history/steno.html"),
    SCI_HUTTON(R.string.ct_science_hutton_source, "https://www.geolsoc.org.uk/science-and-policy/100-great-geosites/historical-scientific-importance/siccar-point/"),
    SCI_LYELL(R.string.ct_science_lyell_source, "https://darwinproject.ac.uk/charles-lyell"),
    SCI_WEGENER(R.string.ct_science_wegener_source, "https://pubs.usgs.gov/gip/dynamic/historical.html"),
    SCI_INNER_CORE(R.string.ct_science_inner_core_source, "https://blogs.egu.eu/divisions/sm/2023/03/08/iwd-2023-inge-lehmann/"),
    SCI_RADIOCARBON(R.string.ct_science_radiocarbon_source, "https://www.acs.org/education/whatischemistry/landmarks/radiocarbon-dating.html"),
    SCI_KEELING(R.string.ct_science_keeling_source, "https://keelingcurve.ucsd.edu/2013/04/03/the-history-of-the-keeling-curve/"),
    SCI_OZONE(R.string.ct_science_ozone_source, "https://www.bas.ac.uk/news/marking-40-years-since-the-discovery-of-the-ozone-hole/"),
    SCI_PLATE_TECTONICS(R.string.ct_science_plate_tectonics_source, "https://www.nature.com/articles/2161276a0"),
    SCI_LOVELACE(R.string.ct_science_lovelace_source, "https://www.computerhistory.org/babbage/adalovelace/"),
    SCI_TURING(R.string.ct_science_turing_source, "https://www.turing.ac.uk/blog/alan-turings-legacy-troubled-times"),
    SCI_ENIAC(R.string.ct_science_eniac_source, "https://penntoday.upenn.edu/news/eniacs-anniversary-nod-its-female-computers"),
    SCI_TRANSISTOR(R.string.ct_science_transistor_source, "https://www.computerhistory.org/siliconengine/invention-of-the-point-contact-transistor/"),
    SCI_SHANNON(R.string.ct_science_shannon_source, "https://web.mit.edu/6.976/www/handout/shannon.pdf"),
    SCI_INTEGRATED_CIRCUIT(R.string.ct_science_integrated_circuit_source, "https://www.computerhistory.org/siliconengine/practical-monolithic-integrated-circuit-concept-patented/"),
    SCI_ARPANET(R.string.ct_science_arpanet_source, "https://www.lk.cs.ucla.edu/internet_first_words.html"),
    SCI_EUCLID_CONTEXT(R.string.ct_science_source_euclid_context, "https://mathshistory.st-andrews.ac.uk/Biographies/Euclid/"),
    SCI_ALGEBRA_DATING(R.string.ct_science_source_algebra_dating, "https://mathshistory.st-andrews.ac.uk/DSB/Khayyam.pdf"),
    SCI_BHASKARA_CONTEXT(R.string.ct_science_source_bhaskara_context, "https://mathshistory.st-andrews.ac.uk/Biographies//Bhaskara_II/"),
    SCI_MAXWELL_CONTEXT(R.string.ct_science_source_maxwell_context, "https://www.royalsociety.org/-/media/journals/publishing/publishing-350-exhibition-catalogue.pdf"),
    SCI_GAGARIN_RETURN(R.string.ct_science_source_gagarin_return, "https://www.nasa.gov/image-article/april-1961-first-human-entered-space/"),
    SCI_CMB_INTERPRETATION(R.string.ct_science_source_cmb_interpretation, "https://pds.nasa.gov/ds-view/pds/viewContext.jsp?identifier=urn%3Anasa%3Apds%3Acontext%3Atarget%3Aastrophysical.cosmic_background"),
    SCI_DNA_PAPERS(R.string.ct_science_source_dna_papers, "https://www.nature.com/articles/d41586-019-01347-8"),
    SCI_HGP_ANNOUNCEMENT(R.string.ct_science_source_hgp_announcement, "https://www.genome.gov/11006929/2003-release-international-consortium-completes-hgp"),
    SCI_PCR_LECTURE(R.string.ct_science_source_pcr_lecture, "https://www.nobelprize.org/prizes/chemistry/1993/mullis/lecture/"),
    SCI_MENDEL_INHERITANCE(R.string.ct_science_source_mendel_inheritance, "https://www.genome.gov/25520230/online-education-kit-1865-mendels-peas"),
    SCI_HOOKE_CORK(R.string.ct_science_source_hooke_cork, "https://prints.royalsociety.org/collections/vintage-antique-physics-science-prints/products/microscopic-view-of-cells-in-a-sliver-of-cork-rs-8428?variant=57888129384829"),
    SCI_KILBY_PROTOTYPE(R.string.ct_science_source_kilby_prototype, "https://www.computerhistory.org/revolution/digital-logic/12/276"),
    SCI_RAMAN_LECTURE(R.string.ct_science_source_raman_lecture, "https://www.nobelprize.org/uploads/2018/06/raman-lecture.pdf")
}

object HumanLandmarks {
    val all = (listOf(
        HumanLandmark("sapiens", HumanRange(ago(300_000), ago(300_000)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_sapiens_title, R.string.ct_history_sapiens_body,
            R.string.ct_history_sapiens_precision, HumanSource.SAPIENS),
        HumanLandmark("sahul", HumanRange(ago(65_000), ago(50_000)), setOf(HumanRegion.OCEANIA),
            R.string.ct_history_sahul_title, R.string.ct_history_sahul_body,
            R.string.ct_history_sahul_precision, HumanSource.SAHUL, uncertainRange = true),
        HumanLandmark("catal", HumanRange(bce(7400, true), bce(6200, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_catal_title, R.string.ct_history_catal_body,
            R.string.ct_history_catal_precision, HumanSource.CATAL),
        HumanLandmark("uruk", HumanRange(bce(3400, true), bce(3000, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_uruk_title, R.string.ct_history_uruk_body,
            R.string.ct_history_uruk_precision, HumanSource.URUK),
        HumanLandmark("dholavira", HumanRange(bce(3000, true), bce(1500, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_dholavira_title, R.string.ct_history_dholavira_body,
            R.string.ct_history_dholavira_precision, HumanSource.DHOLAVIRA),
        HumanLandmark("caral", HumanRange(bce(3000, true), bce(1800, true)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_caral_title, R.string.ct_history_caral_body,
            R.string.ct_history_caral_precision, HumanSource.CARAL),
        HumanLandmark("oldkingdom", HumanRange(bce(2649, true), bce(2130, true)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_oldkingdom_title, R.string.ct_history_oldkingdom_body,
            R.string.ct_history_oldkingdom_precision, HumanSource.OLDKINGDOM),
        HumanLandmark("shang", HumanRange(bce(1600, true), bce(1046, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_shang_title, R.string.ct_history_shang_body,
            R.string.ct_history_shang_precision, HumanSource.SHANG),
        HumanLandmark("han", HumanRange(bce(206), ce(220)), setOf(HumanRegion.ASIA),
            R.string.ct_history_han_title, R.string.ct_history_han_body,
            R.string.ct_history_han_precision, HumanSource.HAN),
        HumanLandmark("rome", HumanRange(bce(27), ce(476)), setOf(HumanRegion.EUROPE, HumanRegion.AFRICA, HumanRegion.ASIA),
            R.string.ct_history_rome_title, R.string.ct_history_rome_body,
            R.string.ct_history_rome_precision, HumanSource.ROME),
        HumanLandmark("maya", HumanRange(ce(250, true), ce(900, true)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_maya_title, R.string.ct_history_maya_body,
            R.string.ct_history_maya_precision, HumanSource.MAYA),
        HumanLandmark("tang", HumanRange(ce(618), ce(907)), setOf(HumanRegion.ASIA),
            R.string.ct_history_tang_title, R.string.ct_history_tang_body,
            R.string.ct_history_tang_precision, HumanSource.TANG),
        HumanLandmark("umayyads", HumanRange(ce(661), ce(750)), setOf(HumanRegion.ASIA, HumanRegion.AFRICA, HumanRegion.EUROPE),
            R.string.ct_history_umayyads_title, R.string.ct_history_umayyads_body,
            R.string.ct_history_umayyads_precision, HumanSource.UMAYYADS),
        HumanLandmark("angkor", HumanRange(ce(800, true), ce(1500, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_angkor_title, R.string.ct_history_angkor_body,
            R.string.ct_history_angkor_precision, HumanSource.ANGKOR),
        HumanLandmark("zimbabwe", HumanRange(ce(1100, true), ce(1450, true)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_zimbabwe_title, R.string.ct_history_zimbabwe_body,
            R.string.ct_history_zimbabwe_precision, HumanSource.ZIMBABWE),
        HumanLandmark("maori", HumanRange(ce(1250, true), ce(1300, true)), setOf(HumanRegion.OCEANIA),
            R.string.ct_history_maori_title, R.string.ct_history_maori_body,
            R.string.ct_history_maori_precision, HumanSource.MAORI, uncertainRange = true),
        HumanLandmark("mansa", HumanRange(ce(1324), ce(1324)), setOf(HumanRegion.AFRICA, HumanRegion.ASIA),
            R.string.ct_history_mansa_title, R.string.ct_history_mansa_body,
            R.string.ct_history_mansa_precision, HumanSource.MANSA),
        HumanLandmark("slave_trade", HumanRange(ce(1501), ce(1866)), setOf(HumanRegion.AFRICA, HumanRegion.AMERICAS, HumanRegion.EUROPE),
            R.string.ct_history_slave_trade_title, R.string.ct_history_slave_trade_body,
            R.string.ct_history_slave_trade_precision, HumanSource.SLAVE_TRADE),
        HumanLandmark("steam", HumanRange(ce(1760, true), ce(1830, true)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_steam_title, R.string.ct_history_steam_body,
            R.string.ct_history_steam_precision, HumanSource.STEAM),
        HumanLandmark("us_independence", HumanRange(ce(1776), ce(1776)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_us_independence_title, R.string.ct_history_us_independence_body,
            R.string.ct_history_us_independence_precision, HumanSource.US_INDEPENDENCE),
        HumanLandmark("french_rights", HumanRange(ce(1789), ce(1789)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_french_rights_title, R.string.ct_history_french_rights_body,
            R.string.ct_history_french_rights_precision, HumanSource.FRENCH_RIGHTS),
        HumanLandmark("haiti", HumanRange(ce(1804), ce(1804)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_haiti_title, R.string.ct_history_haiti_body,
            R.string.ct_history_haiti_precision, HumanSource.HAITI),
        HumanLandmark("meiji", HumanRange(ce(1868), ce(1912)), setOf(HumanRegion.ASIA),
            R.string.ct_history_meiji_title, R.string.ct_history_meiji_body,
            R.string.ct_history_meiji_precision, HumanSource.MEIJI),
        HumanLandmark("ww1", HumanRange(ce(1914), ce(1918)), setOf(HumanRegion.WORLD),
            R.string.ct_history_ww1_title, R.string.ct_history_ww1_body,
            R.string.ct_history_ww1_precision, HumanSource.WW1),
        HumanLandmark("ww2", HumanRange(ce(1939), ce(1945)), setOf(HumanRegion.WORLD),
            R.string.ct_history_ww2_title, R.string.ct_history_ww2_body,
            R.string.ct_history_ww2_precision, HumanSource.WW2),
        HumanLandmark("holocaust", HumanRange(ce(1933), ce(1945)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_holocaust_title, R.string.ct_history_holocaust_body,
            R.string.ct_history_holocaust_precision, HumanSource.HOLOCAUST),
        HumanLandmark("un", HumanRange(ce(1945), ce(1945)), setOf(HumanRegion.WORLD),
            R.string.ct_history_un_title, R.string.ct_history_un_body,
            R.string.ct_history_un_precision, HumanSource.UN),
        HumanLandmark("partition", HumanRange(ce(1947), ce(1947)), setOf(HumanRegion.ASIA),
            R.string.ct_history_partition_title, R.string.ct_history_partition_body,
            R.string.ct_history_partition_precision, HumanSource.PARTITION),
        HumanLandmark("udhr", HumanRange(ce(1948), ce(1948)), setOf(HumanRegion.WORLD),
            R.string.ct_history_udhr_title, R.string.ct_history_udhr_body,
            R.string.ct_history_udhr_precision, HumanSource.UDHR),
        HumanLandmark("decolonization", HumanRange(ce(1960), ce(1960)), setOf(HumanRegion.WORLD, HumanRegion.AFRICA, HumanRegion.ASIA),
            R.string.ct_history_decolonization_title, R.string.ct_history_decolonization_body,
            R.string.ct_history_decolonization_precision, HumanSource.DECOLONIZATION),
        HumanLandmark("apollo", HumanRange(ce(1969), ce(1969)), setOf(HumanRegion.WORLD),
            R.string.ct_history_apollo_title, R.string.ct_history_apollo_body,
            R.string.ct_history_apollo_precision, HumanSource.APOLLO, science = ScienceField.ASTRONOMY),
        HumanLandmark("web", HumanRange(ce(1989), ce(1993)), setOf(HumanRegion.WORLD),
            R.string.ct_history_web_title, R.string.ct_history_web_body,
            R.string.ct_history_web_precision, HumanSource.WEB, science = ScienceField.COMPUTING),
        HumanLandmark("south_africa", HumanRange(ce(1994), ce(1994)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_south_africa_title, R.string.ct_history_south_africa_body,
            R.string.ct_history_south_africa_precision, HumanSource.SOUTH_AFRICA),
        HumanLandmark("paris", HumanRange(ce(2015), ce(2015)), setOf(HumanRegion.WORLD),
            R.string.ct_history_paris_title, R.string.ct_history_paris_body,
            R.string.ct_history_paris_precision, HumanSource.PARIS),
        HumanLandmark("egypt_overview", HumanRange(bce(3100, true), bce(30)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_egypt_overview_title, R.string.ct_history_egypt_overview_body,
            R.string.ct_history_egypt_overview_precision, HumanSource.EGYPT_OVERVIEW),
        HumanLandmark("middlekingdom", HumanRange(bce(2030, true), bce(1650, true)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_middlekingdom_title, R.string.ct_history_middlekingdom_body,
            R.string.ct_history_middlekingdom_precision, HumanSource.MIDDLEKINGDOM),
        HumanLandmark("newkingdom", HumanRange(bce(1550, true), bce(1070, true)), setOf(HumanRegion.AFRICA, HumanRegion.ASIA),
            R.string.ct_history_newkingdom_title, R.string.ct_history_newkingdom_body,
            R.string.ct_history_newkingdom_precision, HumanSource.NEWKINGDOM),
        HumanLandmark("lateegypt", HumanRange(bce(664, true), bce(332)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_lateegypt_title, R.string.ct_history_lateegypt_body,
            R.string.ct_history_lateegypt_precision, HumanSource.LATEEGYPT),
        HumanLandmark("hellenistic_egypt", HumanRange(bce(332), bce(30)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_hellenistic_egypt_title, R.string.ct_history_hellenistic_egypt_body,
            R.string.ct_history_hellenistic_egypt_precision, HumanSource.HELLENISTIC_EGYPT),
        HumanLandmark("roman_egypt", HumanRange(bce(30), bce(30)), setOf(HumanRegion.AFRICA, HumanRegion.EUROPE),
            R.string.ct_history_roman_egypt_title, R.string.ct_history_roman_egypt_body,
            R.string.ct_history_roman_egypt_precision, HumanSource.ROMAN_EGYPT),
        HumanLandmark("khufu", HumanRange(bce(2589, true), bce(2566, true)), setOf(HumanRegion.AFRICA),
            R.string.ct_history_khufu_title, R.string.ct_history_khufu_body,
            R.string.ct_history_khufu_precision, HumanSource.KHUFU, uncertainRange = true),
        HumanLandmark("stonehenge", HumanRange(bce(2500, true), bce(2500, true)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_stonehenge_title, R.string.ct_history_stonehenge_body,
            R.string.ct_history_stonehenge_precision, HumanSource.STONEHENGE),
        HumanLandmark("parthenon", HumanRange(bce(447), bce(432)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_parthenon_title, R.string.ct_history_parthenon_body,
            R.string.ct_history_parthenon_precision, HumanSource.PARTHENON),
        HumanLandmark("colosseum", HumanRange(ce(80), ce(80)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_colosseum_title, R.string.ct_history_colosseum_body,
            R.string.ct_history_colosseum_precision, HumanSource.COLOSSEUM),
        HumanLandmark("hagia_sophia", HumanRange(ce(532), ce(537)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_hagia_sophia_title, R.string.ct_history_hagia_sophia_body,
            R.string.ct_history_hagia_sophia_precision, HumanSource.HAGIA_SOPHIA),
        HumanLandmark("borobudur", HumanRange(ce(700, true), ce(900, true)), setOf(HumanRegion.ASIA),
            R.string.ct_history_borobudur_title, R.string.ct_history_borobudur_body,
            R.string.ct_history_borobudur_precision, HumanSource.BOROBUDUR, uncertainRange = true),
        HumanLandmark("notre_dame", HumanRange(ce(1163), ce(1345)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_notre_dame_title, R.string.ct_history_notre_dame_body,
            R.string.ct_history_notre_dame_precision, HumanSource.NOTRE_DAME),
        HumanLandmark("machu_picchu", HumanRange(ce(1400, true), ce(1500, true)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_machu_picchu_title, R.string.ct_history_machu_picchu_body,
            R.string.ct_history_machu_picchu_precision, HumanSource.MACHU_PICCHU, uncertainRange = true),
        HumanLandmark("forbidden_city", HumanRange(ce(1406), ce(1420)), setOf(HumanRegion.ASIA),
            R.string.ct_history_forbidden_city_title, R.string.ct_history_forbidden_city_body,
            R.string.ct_history_forbidden_city_precision, HumanSource.FORBIDDEN_CITY),
        HumanLandmark("taj_mahal", HumanRange(ce(1632, true), ce(1653)), setOf(HumanRegion.ASIA),
            R.string.ct_history_taj_mahal_title, R.string.ct_history_taj_mahal_body,
            R.string.ct_history_taj_mahal_precision, HumanSource.TAJ_MAHAL),
        HumanLandmark("eiffel", HumanRange(ce(1887), ce(1889)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_eiffel_title, R.string.ct_history_eiffel_body,
            R.string.ct_history_eiffel_precision, HumanSource.EIFFEL),
        HumanLandmark("sydney_opera", HumanRange(ce(1959), ce(1973)), setOf(HumanRegion.OCEANIA),
            R.string.ct_history_sydney_opera_title, R.string.ct_history_sydney_opera_body,
            R.string.ct_history_sydney_opera_precision, HumanSource.SYDNEY_OPERA),
        HumanLandmark("kadesh", HumanRange(bce(1274, true), bce(1274, true)), setOf(HumanRegion.ASIA, HumanRegion.AFRICA),
            R.string.ct_history_kadesh_title, R.string.ct_history_kadesh_body,
            R.string.ct_history_kadesh_precision, HumanSource.KADESH),
        HumanLandmark("hastings", HumanRange(ce(1066), ce(1066)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_hastings_title, R.string.ct_history_hastings_body,
            R.string.ct_history_hastings_precision, HumanSource.HASTINGS, exactDate = R.string.ct_history_hastings_date),
        HumanLandmark("hundred_years", HumanRange(ce(1337), ce(1453)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_hundred_years_title, R.string.ct_history_hundred_years_body,
            R.string.ct_history_hundred_years_precision, HumanSource.HUNDRED_YEARS),
        HumanLandmark("waterloo", HumanRange(ce(1815), ce(1815)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_waterloo_title, R.string.ct_history_waterloo_body,
            R.string.ct_history_waterloo_precision, HumanSource.WATERLOO, exactDate = R.string.ct_history_waterloo_date),
        HumanLandmark("us_civil_war", HumanRange(ce(1861), ce(1865)), setOf(HumanRegion.AMERICAS),
            R.string.ct_history_us_civil_war_title, R.string.ct_history_us_civil_war_body,
            R.string.ct_history_us_civil_war_precision, HumanSource.US_CIVIL_WAR),
        HumanLandmark("verdun", HumanRange(ce(1916), ce(1916)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_verdun_title, R.string.ct_history_verdun_body,
            R.string.ct_history_verdun_precision, HumanSource.VERDUN, exactDate = R.string.ct_history_verdun_date),
        HumanLandmark("somme", HumanRange(ce(1916), ce(1916)), setOf(HumanRegion.EUROPE),
            R.string.ct_history_somme_title, R.string.ct_history_somme_body,
            R.string.ct_history_somme_precision, HumanSource.SOMME, exactDate = R.string.ct_history_somme_date),
        HumanLandmark("korea", HumanRange(ce(1950), ce(1953)), setOf(HumanRegion.ASIA),
            R.string.ct_history_korea_title, R.string.ct_history_korea_body,
            R.string.ct_history_korea_precision, HumanSource.KOREA, exactDate = R.string.ct_history_korea_date)
    ) + ScienceLandmarks.all).sortedWith(compareBy<HumanLandmark> { it.range.first.year }.thenBy { it.range.last.year }.thenBy { it.id })
}
