package com.Atom2Universe.app.science.timeline

import com.Atom2Universe.app.R
import com.Atom2Universe.app.science.timeline.HumanHistory.bce
import com.Atom2Universe.app.science.timeline.HumanHistory.ce

/** Original EN/FR records. Dates and references reviewed on 2026-10-06.
 * Publication/observation distinctions are explained by each record's precision resource.
 * Keep groups separate to limit initializer size; the shared catalog sorts all records. */
object ScienceLandmarks {
    val all: List<HumanLandmark> = mathematics() + physics() + astronomy() + chemistry() + biology() + medicine() + earth() + computing()

    private fun mathematics() = listOf(
        HumanLandmark("science_rhind", HumanRange(bce(1550, true), bce(1550, true)),
            setOf(HumanRegion.AFRICA),
            R.string.ct_science_rhind_title, R.string.ct_science_rhind_body,
            R.string.ct_science_rhind_precision, HumanSource.SCI_RHIND,
            science = ScienceField.MATHEMATICS),
        HumanLandmark("science_euclid", HumanRange(bce(300, true), bce(300, true)),
            setOf(HumanRegion.AFRICA),
            R.string.ct_science_euclid_title, R.string.ct_science_euclid_body,
            R.string.ct_science_euclid_precision, HumanSource.SCI_EUCLID,
            science = ScienceField.MATHEMATICS,
            additionalSources = listOf(HumanSource.SCI_EUCLID_CONTEXT)),
        HumanLandmark("science_liu_hui", HumanRange(ce(263), ce(263)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_liu_hui_title, R.string.ct_science_liu_hui_body,
            R.string.ct_science_liu_hui_precision, HumanSource.SCI_LIU_HUI,
            science = ScienceField.MATHEMATICS),
        HumanLandmark("science_aryabhata", HumanRange(ce(499), ce(499)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_aryabhata_title, R.string.ct_science_aryabhata_body,
            R.string.ct_science_aryabhata_precision, HumanSource.SCI_ARYABHATA,
            science = ScienceField.MATHEMATICS),
        HumanLandmark("science_brahmagupta", HumanRange(ce(628), ce(628)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_brahmagupta_title, R.string.ct_science_brahmagupta_body,
            R.string.ct_science_brahmagupta_precision, HumanSource.SCI_BRAHMAGUPTA,
            science = ScienceField.MATHEMATICS),
        HumanLandmark("science_algebra", HumanRange(ce(830, true), ce(830, true)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_algebra_title, R.string.ct_science_algebra_body,
            R.string.ct_science_algebra_precision, HumanSource.SCI_ALGEBRA,
            science = ScienceField.MATHEMATICS,
            additionalSources = listOf(HumanSource.SCI_ALGEBRA_DATING)),
        HumanLandmark("science_bhaskara", HumanRange(ce(1150), ce(1150)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_bhaskara_title, R.string.ct_science_bhaskara_body,
            R.string.ct_science_bhaskara_precision, HumanSource.SCI_BHASKARA,
            science = ScienceField.MATHEMATICS,
            additionalSources = listOf(HumanSource.SCI_BHASKARA_CONTEXT)),
        HumanLandmark("science_calculus", HumanRange(ce(1684), ce(1684)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_calculus_title, R.string.ct_science_calculus_body,
            R.string.ct_science_calculus_precision, HumanSource.SCI_CALCULUS,
            science = ScienceField.MATHEMATICS),
        HumanLandmark("science_noether", HumanRange(ce(1918), ce(1918)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_noether_title, R.string.ct_science_noether_body,
            R.string.ct_science_noether_precision, HumanSource.SCI_NOETHER,
            science = ScienceField.MATHEMATICS)
    )

    private fun physics() = listOf(
        HumanLandmark("science_optics", HumanRange(ce(1015, true), ce(1015, true)),
            setOf(HumanRegion.AFRICA),
            R.string.ct_science_optics_title, R.string.ct_science_optics_body,
            R.string.ct_science_optics_precision, HumanSource.SCI_OPTICS,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_newton", HumanRange(ce(1687), ce(1687)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_newton_title, R.string.ct_science_newton_body,
            R.string.ct_science_newton_precision, HumanSource.SCI_NEWTON,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_volta", HumanRange(ce(1800), ce(1800)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_volta_title, R.string.ct_science_volta_body,
            R.string.ct_science_volta_precision, HumanSource.SCI_VOLTA,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_volta_date),
        HumanLandmark("science_faraday", HumanRange(ce(1831), ce(1831)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_faraday_title, R.string.ct_science_faraday_body,
            R.string.ct_science_faraday_precision, HumanSource.SCI_FARADAY,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_faraday_date),
        HumanLandmark("science_maxwell", HumanRange(ce(1865), ce(1865)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_maxwell_title, R.string.ct_science_maxwell_body,
            R.string.ct_science_maxwell_precision, HumanSource.SCI_MAXWELL,
            science = ScienceField.PHYSICS,
            additionalSources = listOf(HumanSource.SCI_MAXWELL_CONTEXT)),
        HumanLandmark("science_xray", HumanRange(ce(1895), ce(1895)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_xray_title, R.string.ct_science_xray_body,
            R.string.ct_science_xray_precision, HumanSource.SCI_XRAY,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_xray_date),
        HumanLandmark("science_becquerel", HumanRange(ce(1896), ce(1896)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_becquerel_title, R.string.ct_science_becquerel_body,
            R.string.ct_science_becquerel_precision, HumanSource.SCI_BECQUEREL,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_electron", HumanRange(ce(1897), ce(1897)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_electron_title, R.string.ct_science_electron_body,
            R.string.ct_science_electron_precision, HumanSource.SCI_ELECTRON,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_planck", HumanRange(ce(1900), ce(1900)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_planck_title, R.string.ct_science_planck_body,
            R.string.ct_science_planck_precision, HumanSource.SCI_PLANCK,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_relativity", HumanRange(ce(1905), ce(1905)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_relativity_title, R.string.ct_science_relativity_body,
            R.string.ct_science_relativity_precision, HumanSource.SCI_RELATIVITY,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_general_relativity", HumanRange(ce(1915), ce(1915)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_general_relativity_title, R.string.ct_science_general_relativity_body,
            R.string.ct_science_general_relativity_precision, HumanSource.SCI_GENERAL_RELATIVITY,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_nucleus", HumanRange(ce(1911), ce(1911)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_nucleus_title, R.string.ct_science_nucleus_body,
            R.string.ct_science_nucleus_precision, HumanSource.SCI_NUCLEUS,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_quantum", HumanRange(ce(1925), ce(1926)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_quantum_title, R.string.ct_science_quantum_body,
            R.string.ct_science_quantum_precision, HumanSource.SCI_QUANTUM,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_raman", HumanRange(ce(1928), ce(1928)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_raman_title, R.string.ct_science_raman_body,
            R.string.ct_science_raman_precision, HumanSource.SCI_RAMAN,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_raman_date,
            additionalSources = listOf(HumanSource.SCI_RAMAN_LECTURE)),
        HumanLandmark("science_neutron", HumanRange(ce(1932), ce(1932)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_neutron_title, R.string.ct_science_neutron_body,
            R.string.ct_science_neutron_precision, HumanSource.SCI_NEUTRON,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_fission", HumanRange(ce(1938), ce(1939)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_fission_title, R.string.ct_science_fission_body,
            R.string.ct_science_fission_precision, HumanSource.SCI_FISSION,
            science = ScienceField.PHYSICS),
        HumanLandmark("science_laser", HumanRange(ce(1960), ce(1960)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_laser_title, R.string.ct_science_laser_body,
            R.string.ct_science_laser_precision, HumanSource.SCI_LASER,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_laser_date),
        HumanLandmark("science_higgs", HumanRange(ce(2012), ce(2012)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_higgs_title, R.string.ct_science_higgs_body,
            R.string.ct_science_higgs_precision, HumanSource.SCI_HIGGS,
            science = ScienceField.PHYSICS, exactDate = R.string.ct_science_higgs_date)
    )

    private fun astronomy() = listOf(
        HumanLandmark("science_copernicus", HumanRange(ce(1543), ce(1543)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_copernicus_title, R.string.ct_science_copernicus_body,
            R.string.ct_science_copernicus_precision, HumanSource.SCI_COPERNICUS,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_kepler", HumanRange(ce(1609), ce(1619)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_kepler_title, R.string.ct_science_kepler_body,
            R.string.ct_science_kepler_precision, HumanSource.SCI_KEPLER,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_galileo", HumanRange(ce(1610), ce(1610)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_galileo_title, R.string.ct_science_galileo_body,
            R.string.ct_science_galileo_precision, HumanSource.SCI_GALILEO,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_leavitt", HumanRange(ce(1912), ce(1912)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_leavitt_title, R.string.ct_science_leavitt_body,
            R.string.ct_science_leavitt_precision, HumanSource.SCI_LEAVITT,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_payne", HumanRange(ce(1925), ce(1925)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_payne_title, R.string.ct_science_payne_body,
            R.string.ct_science_payne_precision, HumanSource.SCI_PAYNE,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_lemaitre", HumanRange(ce(1927), ce(1927)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_lemaitre_title, R.string.ct_science_lemaitre_body,
            R.string.ct_science_lemaitre_precision, HumanSource.SCI_LEMAITRE,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_hubble", HumanRange(ce(1929), ce(1929)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_hubble_title, R.string.ct_science_hubble_body,
            R.string.ct_science_hubble_precision, HumanSource.SCI_HUBBLE,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_sputnik", HumanRange(ce(1957), ce(1957)),
            setOf(HumanRegion.EUROPE, HumanRegion.ASIA),
            R.string.ct_science_sputnik_title, R.string.ct_science_sputnik_body,
            R.string.ct_science_sputnik_precision, HumanSource.SCI_SPUTNIK,
            science = ScienceField.ASTRONOMY, exactDate = R.string.ct_science_sputnik_date),
        HumanLandmark("science_gagarin", HumanRange(ce(1961), ce(1961)),
            setOf(HumanRegion.EUROPE, HumanRegion.ASIA),
            R.string.ct_science_gagarin_title, R.string.ct_science_gagarin_body,
            R.string.ct_science_gagarin_precision, HumanSource.SCI_GAGARIN,
            science = ScienceField.ASTRONOMY, exactDate = R.string.ct_science_gagarin_date,
            additionalSources = listOf(HumanSource.SCI_GAGARIN_RETURN)),
        HumanLandmark("science_cmb", HumanRange(ce(1965), ce(1965)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_cmb_title, R.string.ct_science_cmb_body,
            R.string.ct_science_cmb_precision, HumanSource.SCI_CMB,
            science = ScienceField.ASTRONOMY,
            additionalSources = listOf(HumanSource.SCI_CMB_INTERPRETATION)),
        HumanLandmark("science_pulsar", HumanRange(ce(1967), ce(1967)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_pulsar_title, R.string.ct_science_pulsar_body,
            R.string.ct_science_pulsar_precision, HumanSource.SCI_PULSAR,
            science = ScienceField.ASTRONOMY),
        HumanLandmark("science_exoplanet", HumanRange(ce(1995), ce(1995)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_exoplanet_title, R.string.ct_science_exoplanet_body,
            R.string.ct_science_exoplanet_precision, HumanSource.SCI_EXOPLANET,
            science = ScienceField.ASTRONOMY, exactDate = R.string.ct_science_exoplanet_date),
        HumanLandmark("science_gravitational_waves", HumanRange(ce(2015), ce(2015)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_gravitational_waves_title, R.string.ct_science_gravitational_waves_body,
            R.string.ct_science_gravitational_waves_precision, HumanSource.SCI_GRAVITATIONAL_WAVES,
            science = ScienceField.ASTRONOMY, exactDate = R.string.ct_science_gravitational_waves_date),
        HumanLandmark("science_black_hole_image", HumanRange(ce(2019), ce(2019)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_black_hole_image_title, R.string.ct_science_black_hole_image_body,
            R.string.ct_science_black_hole_image_precision, HumanSource.SCI_BLACK_HOLE_IMAGE,
            science = ScienceField.ASTRONOMY, exactDate = R.string.ct_science_black_hole_image_date)
    )

    private fun chemistry() = listOf(
        HumanLandmark("science_lavoisier", HumanRange(ce(1789), ce(1789)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_lavoisier_title, R.string.ct_science_lavoisier_body,
            R.string.ct_science_lavoisier_precision, HumanSource.SCI_LAVOISIER,
            science = ScienceField.CHEMISTRY),
        HumanLandmark("science_dalton", HumanRange(ce(1808), ce(1808)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_dalton_title, R.string.ct_science_dalton_body,
            R.string.ct_science_dalton_precision, HumanSource.SCI_DALTON,
            science = ScienceField.CHEMISTRY),
        HumanLandmark("science_periodic_table", HumanRange(ce(1869), ce(1869)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_periodic_table_title, R.string.ct_science_periodic_table_body,
            R.string.ct_science_periodic_table_precision, HumanSource.SCI_PERIODIC_TABLE,
            science = ScienceField.CHEMISTRY),
        HumanLandmark("science_curie", HumanRange(ce(1898), ce(1898)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_curie_title, R.string.ct_science_curie_body,
            R.string.ct_science_curie_precision, HumanSource.SCI_CURIE,
            science = ScienceField.CHEMISTRY),
        HumanLandmark("science_ammonia", HumanRange(ce(1913), ce(1913)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_ammonia_title, R.string.ct_science_ammonia_body,
            R.string.ct_science_ammonia_precision, HumanSource.SCI_AMMONIA,
            science = ScienceField.CHEMISTRY),
        HumanLandmark("science_fullerene", HumanRange(ce(1985), ce(1985)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_fullerene_title, R.string.ct_science_fullerene_body,
            R.string.ct_science_fullerene_precision, HumanSource.SCI_FULLERENE,
            science = ScienceField.CHEMISTRY)
    )

    private fun biology() = listOf(
        HumanLandmark("science_hooke", HumanRange(ce(1665), ce(1665)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_hooke_title, R.string.ct_science_hooke_body,
            R.string.ct_science_hooke_precision, HumanSource.SCI_HOOKE,
            science = ScienceField.BIOLOGY,
            additionalSources = listOf(HumanSource.SCI_HOOKE_CORK)),
        HumanLandmark("science_leeuwenhoek", HumanRange(ce(1676), ce(1676)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_leeuwenhoek_title, R.string.ct_science_leeuwenhoek_body,
            R.string.ct_science_leeuwenhoek_precision, HumanSource.SCI_LEEUWENHOEK,
            science = ScienceField.BIOLOGY, exactDate = R.string.ct_science_leeuwenhoek_date),
        HumanLandmark("science_linnaeus", HumanRange(ce(1753), ce(1753)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_linnaeus_title, R.string.ct_science_linnaeus_body,
            R.string.ct_science_linnaeus_precision, HumanSource.SCI_LINNAEUS,
            science = ScienceField.BIOLOGY),
        HumanLandmark("science_selection", HumanRange(ce(1858), ce(1859)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_selection_title, R.string.ct_science_selection_body,
            R.string.ct_science_selection_precision, HumanSource.SCI_SELECTION,
            science = ScienceField.BIOLOGY),
        HumanLandmark("science_mendel", HumanRange(ce(1865), ce(1866)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_mendel_title, R.string.ct_science_mendel_body,
            R.string.ct_science_mendel_precision, HumanSource.SCI_MENDEL,
            science = ScienceField.BIOLOGY,
            additionalSources = listOf(HumanSource.SCI_MENDEL_INHERITANCE)),
        HumanLandmark("science_avery", HumanRange(ce(1944), ce(1944)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_avery_title, R.string.ct_science_avery_body,
            R.string.ct_science_avery_precision, HumanSource.SCI_AVERY,
            science = ScienceField.BIOLOGY),
        HumanLandmark("science_dna", HumanRange(ce(1953), ce(1953)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_dna_title, R.string.ct_science_dna_body,
            R.string.ct_science_dna_precision, HumanSource.SCI_DNA,
            science = ScienceField.BIOLOGY, exactDate = R.string.ct_science_dna_date,
            additionalSources = listOf(HumanSource.SCI_DNA_PAPERS)),
        HumanLandmark("science_sequencing", HumanRange(ce(1975), ce(1977)),
            setOf(HumanRegion.EUROPE, HumanRegion.AMERICAS),
            R.string.ct_science_sequencing_title, R.string.ct_science_sequencing_body,
            R.string.ct_science_sequencing_precision, HumanSource.SCI_SEQUENCING,
            science = ScienceField.BIOLOGY),
        HumanLandmark("science_pcr", HumanRange(ce(1983), ce(1983)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_pcr_title, R.string.ct_science_pcr_body,
            R.string.ct_science_pcr_precision, HumanSource.SCI_PCR,
            science = ScienceField.BIOLOGY,
            additionalSources = listOf(HumanSource.SCI_PCR_LECTURE)),
        HumanLandmark("science_human_genome", HumanRange(ce(2003), ce(2003)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_human_genome_title, R.string.ct_science_human_genome_body,
            R.string.ct_science_human_genome_precision, HumanSource.SCI_HUMAN_GENOME,
            science = ScienceField.BIOLOGY, exactDate = R.string.ct_science_human_genome_date,
            additionalSources = listOf(HumanSource.SCI_HGP_ANNOUNCEMENT)),
        HumanLandmark("science_crispr", HumanRange(ce(2012), ce(2012)),
            setOf(HumanRegion.EUROPE, HumanRegion.AMERICAS),
            R.string.ct_science_crispr_title, R.string.ct_science_crispr_body,
            R.string.ct_science_crispr_precision, HumanSource.SCI_CRISPR,
            science = ScienceField.BIOLOGY, exactDate = R.string.ct_science_crispr_date),
        HumanLandmark("science_t2t", HumanRange(ce(2022), ce(2022)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_t2t_title, R.string.ct_science_t2t_body,
            R.string.ct_science_t2t_precision, HumanSource.SCI_T2T,
            science = ScienceField.BIOLOGY, exactDate = R.string.ct_science_t2t_date)
    )

    private fun medicine() = listOf(
        HumanLandmark("science_vesalius", HumanRange(ce(1543), ce(1543)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_vesalius_title, R.string.ct_science_vesalius_body,
            R.string.ct_science_vesalius_precision, HumanSource.SCI_VESALIUS,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_harvey", HumanRange(ce(1628), ce(1628)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_harvey_title, R.string.ct_science_harvey_body,
            R.string.ct_science_harvey_precision, HumanSource.SCI_HARVEY,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_jenner", HumanRange(ce(1796), ce(1796)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_jenner_title, R.string.ct_science_jenner_body,
            R.string.ct_science_jenner_precision, HumanSource.SCI_JENNER,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_semmelweis", HumanRange(ce(1847), ce(1847)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_semmelweis_title, R.string.ct_science_semmelweis_body,
            R.string.ct_science_semmelweis_precision, HumanSource.SCI_SEMMELWEIS,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_snow", HumanRange(ce(1854), ce(1854)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_snow_title, R.string.ct_science_snow_body,
            R.string.ct_science_snow_precision, HumanSource.SCI_SNOW,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_rabies", HumanRange(ce(1885), ce(1885)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_rabies_title, R.string.ct_science_rabies_body,
            R.string.ct_science_rabies_precision, HumanSource.SCI_RABIES,
            science = ScienceField.MEDICINE, exactDate = R.string.ct_science_rabies_date),
        HumanLandmark("science_insulin", HumanRange(ce(1921), ce(1922)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_insulin_title, R.string.ct_science_insulin_body,
            R.string.ct_science_insulin_precision, HumanSource.SCI_INSULIN,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_penicillin", HumanRange(ce(1928), ce(1928)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_penicillin_title, R.string.ct_science_penicillin_body,
            R.string.ct_science_penicillin_precision, HumanSource.SCI_PENICILLIN,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_artemisinin", HumanRange(ce(1972), ce(1972)),
            setOf(HumanRegion.ASIA),
            R.string.ct_science_artemisinin_title, R.string.ct_science_artemisinin_body,
            R.string.ct_science_artemisinin_precision, HumanSource.SCI_ARTEMISININ,
            science = ScienceField.MEDICINE),
        HumanLandmark("science_smallpox", HumanRange(ce(1980), ce(1980)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_smallpox_title, R.string.ct_science_smallpox_body,
            R.string.ct_science_smallpox_precision, HumanSource.SCI_SMALLPOX,
            science = ScienceField.MEDICINE, exactDate = R.string.ct_science_smallpox_date)
    )

    private fun earth() = listOf(
        HumanLandmark("science_steno", HumanRange(ce(1669), ce(1669)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_steno_title, R.string.ct_science_steno_body,
            R.string.ct_science_steno_precision, HumanSource.SCI_STENO,
            science = ScienceField.EARTH),
        HumanLandmark("science_hutton", HumanRange(ce(1788), ce(1788)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_hutton_title, R.string.ct_science_hutton_body,
            R.string.ct_science_hutton_precision, HumanSource.SCI_HUTTON,
            science = ScienceField.EARTH),
        HumanLandmark("science_lyell", HumanRange(ce(1830), ce(1833)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_lyell_title, R.string.ct_science_lyell_body,
            R.string.ct_science_lyell_precision, HumanSource.SCI_LYELL,
            science = ScienceField.EARTH),
        HumanLandmark("science_wegener", HumanRange(ce(1912), ce(1912)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_wegener_title, R.string.ct_science_wegener_body,
            R.string.ct_science_wegener_precision, HumanSource.SCI_WEGENER,
            science = ScienceField.EARTH),
        HumanLandmark("science_inner_core", HumanRange(ce(1936), ce(1936)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_inner_core_title, R.string.ct_science_inner_core_body,
            R.string.ct_science_inner_core_precision, HumanSource.SCI_INNER_CORE,
            science = ScienceField.EARTH),
        HumanLandmark("science_radiocarbon", HumanRange(ce(1949), ce(1949)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_radiocarbon_title, R.string.ct_science_radiocarbon_body,
            R.string.ct_science_radiocarbon_precision, HumanSource.SCI_RADIOCARBON,
            science = ScienceField.EARTH),
        HumanLandmark("science_keeling", HumanRange(ce(1958), ce(1958)),
            setOf(HumanRegion.OCEANIA, HumanRegion.AMERICAS),
            R.string.ct_science_keeling_title, R.string.ct_science_keeling_body,
            R.string.ct_science_keeling_precision, HumanSource.SCI_KEELING,
            science = ScienceField.EARTH),
        HumanLandmark("science_ozone", HumanRange(ce(1985), ce(1985)),
            setOf(HumanRegion.WORLD),
            R.string.ct_science_ozone_title, R.string.ct_science_ozone_body,
            R.string.ct_science_ozone_precision, HumanSource.SCI_OZONE,
            science = ScienceField.EARTH, exactDate = R.string.ct_science_ozone_date),
        HumanLandmark("science_plate_tectonics", HumanRange(ce(1967), ce(1967)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_plate_tectonics_title, R.string.ct_science_plate_tectonics_body,
            R.string.ct_science_plate_tectonics_precision, HumanSource.SCI_PLATE_TECTONICS,
            science = ScienceField.EARTH)
    )

    private fun computing() = listOf(
        HumanLandmark("science_lovelace", HumanRange(ce(1843), ce(1843)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_lovelace_title, R.string.ct_science_lovelace_body,
            R.string.ct_science_lovelace_precision, HumanSource.SCI_LOVELACE,
            science = ScienceField.COMPUTING),
        HumanLandmark("science_turing", HumanRange(ce(1936), ce(1936)),
            setOf(HumanRegion.EUROPE),
            R.string.ct_science_turing_title, R.string.ct_science_turing_body,
            R.string.ct_science_turing_precision, HumanSource.SCI_TURING,
            science = ScienceField.COMPUTING),
        HumanLandmark("science_eniac", HumanRange(ce(1946), ce(1946)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_eniac_title, R.string.ct_science_eniac_body,
            R.string.ct_science_eniac_precision, HumanSource.SCI_ENIAC,
            science = ScienceField.COMPUTING, exactDate = R.string.ct_science_eniac_date),
        HumanLandmark("science_transistor", HumanRange(ce(1947), ce(1947)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_transistor_title, R.string.ct_science_transistor_body,
            R.string.ct_science_transistor_precision, HumanSource.SCI_TRANSISTOR,
            science = ScienceField.COMPUTING),
        HumanLandmark("science_shannon", HumanRange(ce(1948), ce(1948)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_shannon_title, R.string.ct_science_shannon_body,
            R.string.ct_science_shannon_precision, HumanSource.SCI_SHANNON,
            science = ScienceField.COMPUTING),
        HumanLandmark("science_integrated_circuit", HumanRange(ce(1958), ce(1959)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_integrated_circuit_title, R.string.ct_science_integrated_circuit_body,
            R.string.ct_science_integrated_circuit_precision, HumanSource.SCI_INTEGRATED_CIRCUIT,
            science = ScienceField.COMPUTING,
            additionalSources = listOf(HumanSource.SCI_KILBY_PROTOTYPE)),
        HumanLandmark("science_arpanet", HumanRange(ce(1969), ce(1969)),
            setOf(HumanRegion.AMERICAS),
            R.string.ct_science_arpanet_title, R.string.ct_science_arpanet_body,
            R.string.ct_science_arpanet_precision, HumanSource.SCI_ARPANET,
            science = ScienceField.COMPUTING, exactDate = R.string.ct_science_arpanet_date)
    )
}
