package com.Atom2Universe.app.games.puzzles.pattern

import com.Atom2Universe.app.R

/**
 * Les images du mode « Images », dessinées à la main, de la plus petite (5×5) à la plus grande
 * (15×15). Chaque lettre est une case noircie (sa couleur ne sert qu'à l'image révélée à la fin et
 * à la galerie), un point une case vide.
 *
 * Le test `KitPuzzlesTest.logimageImages` vérifie que chacune se résout ligne par ligne, sans
 * jamais deviner : une image refusée par le solveur doit être retouchée (une ou deux cases
 * suffisent souvent) ou retirée.
 */
object PatternPictures {
    /**
     * [palette] : les couleurs propres à l'image (grandes images converties) ; la lettre A est la
     * première. Sans palette, la lettre désigne une couleur de [colour]. Une lettre minuscule est
     * une case colorée à la révélation mais qui ne se noircit pas.
     */
    class Picture(val nameRes: Int, val rows: List<String>, val palette: IntArray? = null) {
        val w get() = rows[0].length
        val h get() = rows.size
        fun letter(i: Int) = rows[i / w][i % w]
        fun filled(i: Int) = letter(i).let { it != '.' && !it.isLowerCase() }
        fun coloured(i: Int) = letter(i) != '.'
        fun colourAt(i: Int): Int {
            val l = letter(i).uppercaseChar()
            return palette?.getOrNull(l - 'A') ?: colour(l)
        }
    }

    /** Les couleurs de l'image révélée : un dessin, donc les mêmes en thème clair et sombre. */
    fun colour(letter: Char): Int = when (letter) {
        'R' -> 0xFFE53935 // rouge
        'O' -> 0xFFFB8C00 // orange
        'Y' -> 0xFFFDD835 // jaune
        'G' -> 0xFF43A047 // vert
        'D' -> 0xFF2E7D32 // vert foncé
        'B' -> 0xFF1E88E5 // bleu
        'C' -> 0xFF26C6DA // cyan
        'L' -> 0xFFCFD8DC // gris très clair (blanc cassé)
        'A' -> 0xFF90A4AE // gris acier
        'N' -> 0xFF6D4C41 // brun
        'P' -> 0xFFF06292 // rose
        'S' -> 0xFFFFCC80 // sable
        else -> 0xFF263238 // 'K' : presque noir
    }.toInt()

    /** Les dessins faits à la main (5×5 à 15×15), puis les grandes images de [bigPictures]. */
    val all by lazy { handDrawn + bigPictures }

    private val handDrawn = listOf(
        Picture(R.string.pattern_pic_heart, listOf(
            ".R.R.",
            "RRRRR",
            "RRRRR",
            ".RRR.",
            "..R..",
        )),
        Picture(R.string.pattern_pic_star, listOf(
            "..Y..",
            "YYYYY",
            ".YYY.",
            ".Y.Y.",
            "Y...Y",
        )),
        Picture(R.string.pattern_pic_sun, listOf(
            "Y.Y.Y",
            ".YYY.",
            "YYYYY",
            ".YYY.",
            "Y.Y.Y",
        )),
        Picture(R.string.pattern_pic_moon, listOf(
            "..LLL.",
            ".LL...",
            "LL....",
            "LL....",
            ".LL...",
            "..LLL.",
        )),
        Picture(R.string.pattern_pic_fir, listOf(
            "..GG..",
            ".GGGG.",
            "..GG..",
            ".GGGG.",
            "GGGGGG",
            "..NN..",
            "..NN..",
        )),
        Picture(R.string.pattern_pic_tube, listOf(
            "LLLLL",
            ".L.L.",
            ".L.L.",
            ".L.L.",
            ".LGL.",
            ".LGL.",
            ".LGL.",
            ".LGL.",
            "..L..",
        )),
        Picture(R.string.pattern_pic_key, listOf(
            ".YYY.....",
            "YY.YY....",
            "Y...YYYYY",
            "YY.YY.Y.Y",
            ".YYY.....",
        )),
        Picture(R.string.pattern_pic_duck, listOf(
            ".YYY....",
            "OYKY....",
            ".YYY....",
            "..YY...Y",
            ".YYYYYYY",
            ".YYYYYYY",
            "..YYYYY.",
        )),
        Picture(R.string.pattern_pic_bell, listOf(
            "...YY...",
            "..YYYY..",
            ".YYYYYY.",
            ".YYYYYY.",
            ".YYYYYY.",
            "YYYYYYYY",
            "...NN...",
        )),
        Picture(R.string.pattern_pic_apple, listOf(
            "....G..",
            "...NGG.",
            "...N...",
            ".RRNRR.",
            "RRRRRRR",
            "RRRRRRR",
            ".RRRRR.",
            "..R.R..",
        )),
        Picture(R.string.pattern_pic_mushroom, listOf(
            "..RRRR..",
            ".RLRRLR.",
            "RRRRRRRR",
            "RLRRRRLR",
            ".RRRRRR.",
            "..SKSK..",
            "..SSSS..",
            "...SS...",
        )),
        Picture(R.string.pattern_pic_crown, listOf(
            "Y....Y....Y",
            "YY..YYY..YY",
            "YYY.YYY.YYY",
            "YYYYYYYYYYY",
            "YRYYYBYYYRY",
            "YYYYYYYYYYY",
        )),
        Picture(R.string.pattern_pic_ufo, listOf(
            "....CCC....",
            "...CCCCC...",
            ".AAAAAAAAA.",
            "AAYAAYAAYAA",
            ".AAAAAAAAA.",
            ".Y.......Y.",
        )),
        Picture(R.string.pattern_pic_icecream, listOf(
            "..PPP..",
            ".PPPPP.",
            "PPPPPPP",
            "PPPPPPP",
            "SSSSSSS",
            ".SSSSS.",
            ".SSSSS.",
            "..SSS..",
            "..SSS..",
            "...S...",
        )),
        Picture(R.string.pattern_pic_fish, listOf(
            "....OOO...",
            "..OOOOOO.O",
            ".OKOOOOOOO",
            "OOOOOOOOO.",
            ".OOOOOOOOO",
            "..OOOOOO.O",
            "....OOO...",
        )),
        Picture(R.string.pattern_pic_turtle, listOf(
            "...DDDDD....",
            "..DGDDDGD.SS",
            ".DDDGDGDDDSK",
            "SSSSSSSSSS..",
            ".SS....SS...",
            ".SS....SS...",
        )),
        Picture(R.string.pattern_pic_bulb, listOf(
            "..YYYY..",
            ".YYYYYY.",
            "YYYYYYYY",
            "YYYYYYYY",
            "YYYYYYYY",
            ".YYYYYY.",
            "..YYYY..",
            "..AAAA..",
            "..AAAA..",
            "...AA...",
        )),
        Picture(R.string.pattern_pic_sailboat, listOf(
            "....N....",
            "...LNL...",
            "..LLNLL..",
            ".LLLNLLL.",
            "LLLLNLLLL",
            "....N....",
            "RRRRRRRRR",
            ".RRRRRRR.",
            "..RRRRR..",
        )),
        Picture(R.string.pattern_pic_flask, listOf(
            "..LLLLL..",
            "...L.L...",
            "...L.L...",
            "...L.L...",
            "..L...L..",
            ".L.....L.",
            ".LBBBBBL.",
            "LBBBBBBBL",
            "LLLLLLLLL",
        )),
        Picture(R.string.pattern_pic_note, listOf(
            "...KKKKKK",
            "...KKKKKK",
            "...K....K",
            "...K....K",
            "...K....K",
            "...K....K",
            ".KKK..KKK",
            "KKKK.KKKK",
            "KKK..KKK.",
        )),
        Picture(R.string.pattern_pic_umbrella, listOf(
            "....R....",
            "..RRRRR..",
            ".RRRRRRR.",
            "RRRRRRRRR",
            "....N....",
            "....N....",
            "....N....",
            "..N.N....",
            "...N.....",
        )),
        Picture(R.string.pattern_pic_invader, listOf(
            "..G.....G..",
            "...G...G...",
            "..GGGGGGG..",
            ".GG.GGG.GG.",
            "GGGGGGGGGGG",
            "G.GGGGGGG.G",
            "G.G.....G.G",
            "...GG.GG...",
        )),
        Picture(R.string.pattern_pic_crab, listOf(
            "RR.......RR",
            "R.R.....R.R",
            ".RR.K.K.RR.",
            "..R.R.R.R..",
            "..RRRRRRR..",
            ".RRRRRRRRR.",
            "R.RRRRRRR.R",
            ".R.R...R.R.",
        )),
        Picture(R.string.pattern_pic_magnet, listOf(
            "LLL....LLL",
            "LLL....LLL",
            "RRR....BBB",
            "RRR....BBB",
            "RRR....BBB",
            "RRR....BBB",
            "RRRR..BBBB",
            ".RRRRBBBB.",
            "..RRRBBB..",
        )),
        Picture(R.string.pattern_pic_satellite, listOf(
            ".......A.......",
            ".......A.......",
            "BBBB..LLL..BBBB",
            "BBBBAALLLAABBBB",
            "BBBB..LLL..BBBB",
            "......LLL......",
        )),
        Picture(R.string.pattern_pic_comet, listOf(
            "..YYY........",
            ".YYYYYCCCC...",
            "YYYYYYYCCCCCC",
            "YYYYYYYCCCCC.",
            "YYYYYYYCCCCCC",
            ".YYYYYCCCC...",
            "..YYY........",
        )),
        Picture(R.string.pattern_pic_saturn, listOf(
            "....YYYYY....",
            "...YYYYYYY...",
            "OOOOOOOOOOOOO",
            "..YYYYYYYYY..",
            "OOOOOOOOOOOOO",
            "...YYYYYYY...",
            "....YYYYY....",
        )),
        Picture(R.string.pattern_pic_rocket, listOf(
            "....RR....",
            "...RLLR...",
            "...LBBL...",
            "...LBBL...",
            "...LLLL...",
            "...LLLL...",
            "..RLLLLR..",
            ".RRLLLLRR.",
            ".R.OYYO.R.",
            "....OO....",
        )),
        Picture(R.string.pattern_pic_tree, listOf(
            "....GG....",
            "...GGGG...",
            "..GGGGGG..",
            ".GGGDGGGG.",
            "GGGGGGDGGG",
            ".GGDGGGGG.",
            "..GGGGGG..",
            "....NN....",
            "....NN....",
            "..NNNNNN..",
        )),
        Picture(R.string.pattern_pic_cat, listOf(
            ".K......K.",
            ".KK....KK.",
            ".KKKKKKKK.",
            "KKKKKKKKKK",
            "KK.KKKK.KK",
            "KKKKKKKKKK",
            "KKKKPPKKKK",
            ".KKKKKKKK.",
            "..KKKKKK..",
            "...K..K...",
        )),
        Picture(R.string.pattern_pic_car, listOf(
            "...RRRRRRRR...",
            "..RR..RR..RR..",
            ".RRR..RR..RRR.",
            "RRRRRRRRRRRRRR",
            "RRRRRRRRRRRRRR",
            "RRRRRRRRRRRRRR",
            "..KKK....KKK..",
            "..KKK....KKK..",
        )),
        Picture(R.string.pattern_pic_anchor, listOf(
            "....AAA....",
            "....A.A....",
            "....AAA....",
            "..AAAAAAA..",
            ".....A.....",
            ".....A.....",
            ".....A.....",
            "AA...A...AA",
            ".A...A...A.",
            ".AA..A..AA.",
            "..AAAAAAA..",
        )),
        Picture(R.string.pattern_pic_magnifier, listOf(
            "..AAAA.....",
            ".ACCCCA....",
            "ACCCCCCA...",
            "ACCCCCCA...",
            "ACCCCCCA...",
            "ACCCCCCA...",
            ".ACCCCA....",
            "..AAAANN...",
            "......NNN..",
            ".......NNN.",
            "........NN.",
        )),
        Picture(R.string.pattern_pic_snail, listOf(
            "...NNNNN......",
            "..NOOOOON.....",
            ".NOONNNOON.K.K",
            ".NONOOONON.S.S",
            ".NOONNOON..SSS",
            "..NOOOON..SSSS",
            "...NNNN..SSSS.",
            "SSSSSSSSSSSSS.",
            ".SSSSSSSSSSS..",
        )),
        Picture(R.string.pattern_pic_butterfly, listOf(
            "...KK...KK...",
            ".....K.K.....",
            ".PPP..K..PPP.",
            "PPPPP.K.PPPPP",
            "PPYPPPKPPPYPP",
            "PPPPPPKPPPPPP",
            ".PPPP.K.PPPP.",
            ".PPPPPKPPPPP.",
            ".PPOP.K.POPP.",
            "..PP.....PP..",
        )),
        Picture(R.string.pattern_pic_lighthouse, listOf(
            "...RRR...",
            "..RYYYR..",
            ".RRRRRRR.",
            "...RRR...",
            "...LLL...",
            "...LLL...",
            "..RRRRR..",
            "..RRRRR..",
            "..LLLLL..",
            "..LLLLL..",
            ".RRRRRRR.",
            ".RRRRRRR.",
            ".LLLLLLL.",
            ".LLLLLLL.",
            "BBBBBBBBB",
        )),
        Picture(R.string.pattern_pic_telescope, listOf(
            "........BBBBB",
            "....BBBBBBBBB",
            "BBBBBBBBBBBB.",
            "BBBBBBBBB....",
            "......N......",
            "......N......",
            "....NNNNN....",
            "....N.N.N....",
            "...N..N..N...",
            "...N..N..N...",
            "..NN..N..NN..",
        )),
        Picture(R.string.pattern_pic_house, listOf(
            ".....RR.....",
            "....RRRR....",
            "...RRRRRR...",
            "..RRRRRRRR..",
            ".RRRRRRRRRR.",
            "RRRRRRRRRRRR",
            ".NNNNNNNNNN.",
            ".N..NNNN..N.",
            ".N..NNNN..N.",
            ".NNNNN..NNN.",
            ".NNNNN..NNN.",
            "GGGGGGGGGGGG",
        )),
        Picture(R.string.pattern_pic_cup, listOf(
            "....N..N....",
            ".....N..N...",
            "....N..N....",
            "............",
            ".LLLLLLLLL..",
            ".LNNNNNNNL..",
            ".LLLLLLLLLLL",
            ".LLLLLLLLL.L",
            ".LLLLLLLLL.L",
            ".LLLLLLLLLLL",
            "..LLLLLLL...",
            "LLLLLLLLLLLL",
        )),
        Picture(R.string.pattern_pic_earth, listOf(
            "....BBBB....",
            "..BBGGBBBB..",
            ".BBGGGGBBBB.",
            ".BGGGGBBBGB.",
            "BBGGGBBBGGGB",
            "BBBGGBBGGGGB",
            "BBBBGBBGGGBB",
            "BBBBBBBBGBBB",
            ".BBBBBBBBBB.",
            ".BBGGBBBBBB.",
            "..BBBBBBBB..",
            "....BBBB....",
        )),
        Picture(R.string.pattern_pic_whale, listOf(
            "..C.C......B..B",
            "...C.......BBBB",
            ".BBBBB......BB.",
            "BBBBBBBB....BB.",
            "BBKBBBBBBB.BB..",
            "BBBBBBBBBBBBB..",
            "BBBBBBBBBBBB...",
            "LLLLBBBBBBB....",
            ".LLLLLLBBB.....",
            "...LLLL........",
        )),
        Picture(R.string.pattern_pic_penguin, listOf(
            "...KKKKK...",
            "..KKKKKKK..",
            "..KLKKKLK..",
            "..KKOOOKK..",
            "..KKKOKKK..",
            ".KKLLLLLKK.",
            "KKLLLLLLLKK",
            "KKLLLLLLLKK",
            "KKLLLLLLLKK",
            ".KLLLLLLLK.",
            ".KLLLLLLLK.",
            "..KLLLLLK..",
            "..KKKKKKK..",
            ".OOO...OOO.",
        )),
        Picture(R.string.pattern_pic_rabbit, listOf(
            "..AA...AA..",
            "..APA.APA..",
            "..APA.APA..",
            "..APA.APA..",
            "..AAA.AAA..",
            ".AAAAAAAAA.",
            "AAKAAAAAKAA",
            "AAAAAPAAAAA",
            ".AAAAAAAAA.",
            "..AAAAAAA..",
            ".AAAAAAAAA.",
            "AAAAAAAAAAA",
            "AAAAAAAAAAA",
            ".AAA...AAA.",
        )),
        Picture(R.string.pattern_pic_owl, listOf(
            "NN........NN",
            ".NN......NN.",
            ".NNNNNNNNNN.",
            "NLLLNNNNLLLN",
            "NLKLNNNNLKLN",
            "NLLLNOONLLLN",
            ".NNNNOONNNN.",
            ".NSSSSSSSSN.",
            ".NSSSSSSSSN.",
            ".NSSSSSSSSN.",
            "..NSSSSSSN..",
            "...NNNNNN...",
            "...O.O.O.O..",
        )),
        Picture(R.string.pattern_pic_elephant, listOf(
            "..AAA..........",
            ".AAAAA.AAAAAA..",
            "AAAAAAAAAAAAAA.",
            "AKAAAAAAAAAAAAA",
            "AAAAAAAAAAAAAAA",
            "AA.AAAAAAAAAAA.",
            "A..AAAAAAAAAAA.",
            "A..AAA.AAA.AAA.",
            "A..AA..AA..AA..",
            "A..AA..AA..AA..",
            ".A.AA..AA..AA..",
        )),
        Picture(R.string.pattern_pic_atom, listOf(
            "....CCBCC....",
            "....C...C....",
            "....C...C....",
            "C...C...C...C",
            "CCCCCCCCCCCCC",
            "C...CRRRC...B",
            "C...CRRRC...C",
            "B...CRRRC...C",
            "CCCCCCCCCCCCC",
            "C...C...C...C",
            "....C...C....",
            "....C...C....",
            "....CCBCC....",
        )),
        Picture(R.string.pattern_pic_robot, listOf(
            "......R......",
            "......A......",
            "..AAAAAAAAA..",
            "..A.......A..",
            "..A.CC.CC.A..",
            "..A.......A..",
            "..A..RRR..A..",
            "..AAAAAAAAA..",
            "A...AAAAA...A",
            "AAAAAYAYAAAAA",
            "....AAAAA....",
            "....A...A....",
            "....A...A....",
            "...AA...AA...",
        )),
        Picture(R.string.pattern_pic_astronaut, listOf(
            ".....LLLLL.....",
            "...LLLLLLLLL...",
            "..LL.......LL..",
            ".LL.KKKKKKK.LL.",
            ".L.KKKKKKBBK.L.",
            "LL.KKKKKKKBK.LL",
            "LL.KKKKKKKKK.LL",
            "LL.KKKKKKKKK.LL",
            ".L.KKKKKKKKK.L.",
            ".LL.KKKKKKK.LL.",
            "..LL.......LL..",
            "...LLLLLLLLL...",
            ".LLLLLLRLLLLLL.",
            "LLLLLLRRRLLLLLL",
            "LLLLLLLLLLLLLLL",
        )),
    )
}
