"""Generate readable light accents from the existing preset/spectrum styles.

Run after generate_spectrum_themes.py when the color catalogue changes. Only accent
overlays are generated; shapes, surfaces and effects remain independent.
"""
from pathlib import Path
import sys
import xml.etree.ElementTree as ET
sys.dont_write_bytecode = True
from generate_spectrum_themes import contrast, mix, hexa

ROOT = Path(__file__).resolve().parents[2]
VALUES = ROOT / "app/src/main/res/values"
SURFACE = (252, 252, 253)
BACKGROUNDS = [(244, 245, 247), SURFACE, (230, 232, 236)]
SURFACE_TINT_MIX = 0.32


def main():
    colors = {}
    for path in VALUES.glob("*.xml"):
        for el in ET.parse(path).getroot().findall("color"):
            colors[el.attrib["name"]] = el.text.strip()

    def rgb(value):
        while value.startswith("@color/"):
            value = colors[value[7:]]
        value = value.lstrip("#")[-6:]
        return tuple(int(value[i:i+2], 16) for i in (0, 2, 4))

    xml = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/theme/generate_light_themes.py. -->', '<resources>']
    mappings, ratios = [], []
    for file in ("themes.xml", "themes_spectrum.xml"):
        for style in ET.parse(VALUES / file).getroot().findall("style"):
            name = style.attrib["name"]
            if not name.startswith("Theme.A2U."):
                continue
            accent_item = style.find("item[@name='a2uMusicAccent']")
            if accent_item is None:
                continue
            original = rgb(accent_item.text)
            # Keep hue/saturation character; darken only as much as legibility requires.
            for step in range(256):
                accent = mix(original, (0, 0, 0), step / 255)
                dim = mix(SURFACE, original, SURFACE_TINT_MIX)
                checks = [contrast(accent, bg) for bg in BACKGROUNDS + [dim, (255, 255, 255)]]
                if min(checks) >= 4.5:
                    break
            ratios.append(min(checks))
            overlay = name.replace("Theme.A2U.", "ThemeOverlay.A2U.LightAccent.")
            xml += [f'    <style name="{overlay}" parent="">',
                    f'        <item name="a2uMusicAccent">{hexa(accent)}</item>',
                    f'        <item name="a2uMusicAccentDim">{hexa(dim)}</item>',
                    '    </style>']
            mappings.append(f'        R.style.{name.replace(".", "_")} -> R.style.{overlay.replace(".", "_")}')
    xml.append('</resources>')
    (VALUES / 'themes_light_accents.xml').write_text('\n'.join(xml) + '\n', encoding='utf-8')
    kt = '''package com.Atom2Universe.app

// Generated by tools/theme/generate_light_themes.py.
internal object LightAccentThemes {
    fun overlay(colorStyle: Int): Int = when (colorStyle) {
''' + '\n'.join(mappings) + '''
        else -> R.style.ThemeOverlay_A2U_LightAccent_Classic
    }
}
'''
    (ROOT / 'app/src/main/java/com/Atom2Universe/app/LightAccentThemes.kt').write_text(kt, encoding='utf-8')
    print(f'{len(mappings)} light accents; minimum contrast {min(ratios):.2f}:1')


if __name__ == '__main__':
    main()
